[package]
edition = "2021"
license = "Apache 2.0"
name = "datadog-ipc-macros"
version = "0.0.1"

[lib]
proc-macro = true

[dependencies]
syn = { version = "^2", features = ["full", "proc-macro", "parsing", "printing"], default-features = false }
quote = { version = "^1", features = ["proc-macro"], default-features = false }
