[package]
edition = "2021"
license = "Apache 2.0"
name = "datadog-live-debugger"
version = "0.0.1"

[dependencies]
anyhow = "1.0"
ddcommon = { path = "../ddcommon" }
lazy_static = "1.4"
hyper = { version = "0.14", features = ["client"] }
regex = "1.9.3"
json = "0.12.4"
percent-encoding = "2.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sys-info = { version = "0.9.0" }
uuid = { version = "1.0", features = ["v4"] }
regex-automata = "0.4.5"
