# Copyright 2021-Present Datadog, Inc. https://www.datadoghq.com/
# SPDX-License-Identifier: Apache-2.0

[package]
name = "libdd-sidecar-ffi"
version = "0.0.1"
edition = "2021"
publish = false

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
bench = false

[dependencies]
ddtelemetry = { version = "1.0.0", path = "../libdd-telemetry", package = "libdd-telemetry" }
datadog-sidecar = { path = "../libdd-sidecar", package = "libdd-sidecar" }
datadog-trace-utils = { version = "1.0.0", path = "../libdd-trace-utils", package = "libdd-trace-utils" }
datadog-ipc = { version = "0.1.0", path = "../libdd-ipc", package = "libdd-ipc" }
ddcommon = { version = "1.0.0", path = "../libdd-common", package = "libdd-common" }
ddcommon-ffi = { path = "../libdd-common-ffi", package = "libdd-common-ffi", default-features = false }
ddtelemetry-ffi = { path = "../libdd-telemetry-ffi", package = "libdd-telemetry-ffi", default-features = false }
datadog-remote-config = { path = "../libdd-remote-config" , package = "libdd-remote-config" }
datadog-live-debugger = { path = "../libdd-live-debugger", package = "libdd-live-debugger" }
dogstatsd-client = { version = "1.0.0", path = "../libdd-dogstatsd-client", package = "libdd-dogstatsd-client" }
tinybytes = { version = "1.0.0", path = "../libdd-tinybytes", package = "libdd-tinybytes", features = ["bytes_string"] }
paste = "1"
libc = "0.2"
tracing = { version = "0.1", default-features = false }
rmp-serde = "1.1.1"


[target.'cfg(windows)'.dependencies]
datadog-crashtracker-ffi = { path = "../libdd-crashtracker-ffi", package = "libdd-crashtracker-ffi", features = ["collector", "collector_windows"] }

[dev-dependencies]
http = "1.0"
tempfile = { version = "3.3" }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    "cfg(coverage_nightly)",
    'cfg(feature, values("prefer_dynamic"))',
] }
