[package]
name = "data-pipline-java"
rust-version.workspace = true
edition.workspace = true
version.workspace = true
license.workspace = true

[lib]
crate_type = ["cdylib"]

[dependencies]
jni = "0.21.1"

data-pipeline = { path = "../data-pipeline" }
