[package]
name = "libdd-data-pipeline-core"
version = "1.0.0"
description = "Runtime-independent request preparation for Datadog APM data pipelines."
homepage = "https://github.com/DataDog/libdatadog/tree/main/libdd-data-pipeline-core"
repository = "https://github.com/DataDog/libdatadog/tree/main/libdd-data-pipeline-core"
rust-version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bytes = "1.11.1"
http = "1"
serde_json.workspace = true
thiserror = "1.0"
libdd-common = { version = "5.2.0", path = "../libdd-common", default-features = false }
libdd-trace-utils = { version = "10.1.0", path = "../libdd-trace-utils", default-features = false }

[dev-dependencies]
libdd-tinybytes = { version = "1.1.2", path = "../libdd-tinybytes", features = ["bytes_string"] }
zstd = { version = "0.13", default-features = false }

[features]
default = []
compression = ["libdd-trace-utils/compression"]
regex-lite = ["libdd-common/regex-lite"]
