[package]
name = "libdd-data-pipeline-core"
version = "0.1.0"
description = "Runtime-independent operations for Datadog APM data pipelines."
homepage = "https://github.com/DataDog/libdatadog/tree/main/libdd-data-pipeline-core"
repository = "https://github.com/DataDog/libdatadog/tree/main/libdd-data-pipeline-core"
rust-version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
http.workspace = true
serde_json.workspace = true
thiserror = "1.0"
libdd-capabilities = { version = "3.0.1", path = "../libdd-capabilities" }
libdd-common = { version = "5.2.0", path = "../libdd-common", default-features = false }
libdd-trace-utils = { version = "11.0.0", path = "../libdd-trace-utils", default-features = false }
libdd-trace-obfuscation = { version = "7.0.0", path = "../libdd-trace-obfuscation", default-features = false }

[dev-dependencies]
bytes.workspace = true
futures = { workspace = true, features = ["executor"] }
libdd-tinybytes = { version = "1.1.2", path = "../libdd-tinybytes", features = ["bytes_string"] }
zstd.workspace = true

[features]
default = []
compression = ["libdd-trace-utils/compression"]
regex-lite = ["libdd-common/regex-lite"]
