#ifndef DDOG_TELEMETRY_API_H
#define DDOG_TELEMETRY_API_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef enum CLogLevel {
  Error = 1,
  Warn = 2,
  Debug = 3,
} CLogLevel;

typedef enum FfiError {
  Ok = 0,
  PointerNull = 1,
  OperationFailed = 2,
  InvalidUtf8 = 3,
  QueueFull = 4,
} FfiError;

typedef struct FfiString {
  const char *ptr;
  uintptr_t len;
} FfiString;

/**
 * Enqueues a telemetry log action to be processed internally.
 * Non-blocking. Logs might be dropped if the internal queue is full.
 *
 * # Safety
 * Pointers must be valid, strings must be null-terminated if not null.
 */
enum FfiError ddog_sidecar_enqueue_telemetry_log(struct FfiString session_id_ffi,
                                                 struct FfiString runtime_id_ffi,
                                                 uint64_t queue_id,
                                                 struct FfiString identifier_ffi,
                                                 enum CLogLevel level,
                                                 struct FfiString message_ffi,
                                                 struct FfiString *stack_trace_ffi,
                                                 struct FfiString *tags_ffi,
                                                 bool is_sensitive);

#endif  /* DDOG_TELEMETRY_API_H */
