[package]
name = "datadog-trace-utils"
authors = ["David Lee <david.lee@datadoghq.com>"]
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0"
hyper = { version = "0.14", features = ["client", "server"] }
hyper-rustls = {version = "0.27", default-features = false, features = ["native-tokio", "http1", "tls12"]}
serde = { version = "1.0.145", features = ["derive"] }
prost = "0.11.6"
rmp-serde = "1.1.1"
log = "0.4"
serde_json = "1.0"
flate2 = "1.0"
futures = { version = "0.3", default-features = false }
ddcommon = { path = "../ddcommon" }
datadog-trace-protobuf = { path = "../trace-protobuf" }
datadog-trace-normalization = { path = "../trace-normalization" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
rand = "0.8.5"
bytes = "1.6.0"
# This should only be used for testing. It isn't under dev-dependencies because test-utils can't be under #[cfg(test)].
httpmock = { version = "0.7.0", optional = true}
rmpv = { version = "1.3.0", default-features = false }
rmp = { version = "0.8.14", default-features = false }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde_json = "1.0"
httpmock = { version = "0.7.0"}

[features]
test-utils = ["httpmock"]
