[package]
name = "datadog-trace-utils"
version = "2.1.0"
authors = ["David Lee <david.lee@datadoghq.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0"
hyper = { version = "0.14", features = ["full"] }
hyper-tls = "0.5.0"
serde = { version = "1.0.145", features = ["derive"] }
prost = "0.11.6"
rmp-serde = "1.1.1"
datadog-trace-protobuf = { path = "../trace-protobuf" }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde_json = "1.0"