[package]
name = "datadog-trace-utils"
authors = ["David Lee <david.lee@datadoghq.com>"]
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0"
hyper = { version = "0.14", features = ["client", "server"] }
serde = { version = "1.0.145", features = ["derive"] }
prost = "0.11.6"
rmp-serde = "1.1.1"
log = "0.4"
serde_json = "1.0"
flate2 = "1.0"
futures = { version = "0.3", default-features = false }
ddcommon = { path = "../ddcommon", default-features = false }
datadog-trace-protobuf = { path = "../trace-protobuf" }
datadog-trace-normalization = { path = "../trace-normalization" }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde_json = "1.0"
