// Copyright 2021-Present Datadog, Inc. https://www.datadoghq.com/
// SPDX-License-Identifier: Apache-2.0

// This build script always runs on the host with std available (the `no_std` library it builds
// has nothing to do with the build script's own environment), so the workspace-wide
// std-vs-core/alloc and expect-used lints (meant to guard the library itself) don't apply here.
#![allow(
    clippy::std_instead_of_core,
    clippy::std_instead_of_alloc,
    clippy::expect_used
)]

fn main() {
    #[cfg(feature = "generate-protobuf")]
    generate::run().expect("failed to regenerate protobuf bindings from proto/intake_v3.proto");
    #[cfg(not(feature = "generate-protobuf"))]
    println!("cargo:rerun-if-changed=build.rs");
}

/// Regenerates `tests/pb/mod.rs` from `proto/intake_v3.proto`. Only compiled when the
/// `generate-protobuf` feature is enabled, since it's the only fallible part of this build
/// script: normal builds and test runs use the checked-in `tests/pb/mod.rs` and never reach it.
#[cfg(feature = "generate-protobuf")]
mod generate {
    use std::error::Error;
    use std::{env, fs, path::Path};

    const HEADER: &str = "// Copyright 2021-Present Datadog, Inc. https://www.datadoghq.com/
// SPDX-License-Identifier: Apache-2.0

// This file is @generated by prost-build from `proto/intake_v3.proto`. Do not edit it directly:
// regenerate it with `cargo build -p libdd-metrics-v3 --features generate-protobuf` after
// changing the vendored .proto file.
#![allow(dead_code, clippy::all, clippy::pedantic, clippy::nursery)]

";

    pub fn run() -> Result<(), Box<dyn Error>> {
        // protoc is required to compile proto files. This uses protoc-bin-vendored to obtain a
        // protoc binary, setting the env var to tell prost-build where to find it.
        env::set_var("PROTOC", protoc_bin_vendored::protoc_bin_path()?);

        let cur_working_dir = env::var("CARGO_MANIFEST_DIR")?;
        let out_dir = Path::new(&cur_working_dir).join("tests/pb");
        fs::create_dir_all(&out_dir)?;

        let mut config = prost_build::Config::new();
        config.out_dir(&out_dir);

        println!("cargo:rerun-if-changed=proto/intake_v3.proto");
        config.compile_protos(&["proto/intake_v3.proto"], &["proto"])?;

        // prost-build names the output file after the proto's package
        // (`datadoghq.api.metrics.v3.rs`); rename it to `mod.rs` so `tests/parity.rs` can
        // pull it in as a plain submodule.
        let generated = out_dir.join("datadoghq.api.metrics.v3.rs");
        let mod_rs = out_dir.join("mod.rs");
        fs::rename(&generated, &mod_rs)?;

        prepend_to_file(HEADER.as_bytes(), &mod_rs)?;

        Ok(())
    }

    fn prepend_to_file(data: &[u8], file_path: &Path) -> Result<(), Box<dyn Error>> {
        use std::io::{Read, Write};

        let mut f = fs::File::open(file_path)?;
        let mut content = data.to_owned();
        f.read_to_end(&mut content)?;

        let mut f = fs::File::create(file_path)?;
        f.write_all(content.as_slice())?;
        Ok(())
    }
}
