# Unless explicitly stated otherwise all files in this repository are licensed under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2021-Present Datadog, Inc.

[package]
name = "datadog-profiling"
version = "0.8.0-alpha.1"
edition = "2021"
build = "build.rs"
license = "Apache-2.0"

[lib]
# LTO is ignored if "lib" is added as crate type
# cf. https://github.com/rust-lang/rust/issues/51009
crate-type = ["cdylib", "staticlib", "lib"]

[features]
default = []
datadog_profiling_ffi = ["dep:ddcommon-ffi"]

[build-dependencies]
prost-build = "0.10"

[dependencies]
anyhow = "1.0"
bytes = "1.1"
chrono = "0.4"
ddcommon = {path = "../ddcommon"}
ddcommon-ffi = { path = "../ddcommon-ffi", optional = true }
futures = "0.3"
futures-core = {version = "0.3.0", default-features = false}
futures-util = {version = "0.3.0", default-features = false}
http = "0.2"
http-body = "0.4"
hyper = {version = "0.14", features = ["client"], default-features = false}
hyper-multipart-rfc7578 = "0.7.0"
indexmap = "1.8"
libc = "0.2"
mime_guess = {version = "2.0", default-features = false}
percent-encoding = "2.1"
prost = "0.10"
tokio = {version = "1.8", features = ["rt", "macros"]}
tokio-util = "0.7.1"
