# Copyright 2021-Present Datadog, Inc. https://www.datadoghq.com/
# SPDX-License-Identifier: Apache-2.0

[package]
name = "datadog-profiling"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license.workspace = true
autobenches = false

[lib]
crate-type = ["lib"]
bench = false

[[bench]]
name = "main"
harness = false

[dependencies]
anyhow = "1.0"
bitmaps = "3.2.0"
byteorder = { version = "1.5", features = ["std"] }
bytes = "1.1"
chrono = {version = "0.4", default-features = false, features = ["std", "clock"]}
datadog-alloc = {path = "../alloc"}
ddcommon = { path = "../ddcommon" }
ddcommon-net2 = { path = "../ddcommon-net2", features = ["use_native_roots"] }
derivative = "2.2.0"
hashbrown = { version = "0.14", default-features = false, features = ["allocator-api2"] }
hyper-multipart-rfc7578 = { git = "https://github.com/jothan/rust-hyper-multipart-rfc7578.git", rev = "4d3064a7a8c0062b485d50e4460cb7ad71c83d35" }
indexmap = "2.2"
libc = "0.2"
lz4_flex = { version = "0.9", default-features = false, features = ["std", "safe-encode", "frame"] }
mime = "0.3.16"
mime_guess = {version = "2.0", default-features = false}
percent-encoding = "2.1"
prost = "0.12"
rustc-hash = { version = "1.1", default-features = false }
serde = {version = "1.0", features = ["derive"]}
serde_json = {version = "1.0"}
tokio = {version = "1.23", features = ["rt", "macros"]}
tokio-util = "0.7.1"
rustls-native-certs = "0.8.1"

[dev-dependencies]
bolero = "0.10.1"
bolero-generator = "0.10.2"
criterion = "0.5.1"
futures = { version = "0.3", default-features = false }
http-body-util = "0.1"
