codecov:
  require_ci_to_pass: false

comment:
    layout: "condensed_header, diff, flags, components, condensed_footer"
    hide_project_coverage: false

coverage:
  precision: 2
  round: down
  range: "70...95"

ignore:
  - "bin_tests/**"

components:
  individual_components:
