unstable_features = true

ignore = [
  # embedded project waiting for upstream fixes
  "crates/datadog-ipc/tarpc/",
]

format_macro_matchers = true
format_code_in_doc_comments=true
wrap_comments = true
max_width=100
comment_width=100
doc_comment_code_block_width=100
