[package]
name = "serverless-preload"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
datadog-metrics = { path = "../metrics" }
tokio = { version = "1.27.0", features = ["net", "rt", "rt-multi-thread", "macros"] }
