# Copyright 2026-Present Datadog, Inc. https://www.datadoghq.com/
# SPDX-License-Identifier: Apache-2.0

[package]
name = "libdd-wasm-tests"
version = "0.0.1"
publish = false
edition.workspace = true
rust-version.workspace = true
license.workspace = true
autolib = false

[features]
default = ["compression"]
compression = []

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
http = { workspace = true, default-features = true }
wasm-bindgen-test = { workspace = true, default-features = true }
zrip = { workspace = true, features = ["frame"] }
