[package]
name = "datadog-trace-normalization"
authors = ["David Lee <david.lee@datadoghq.com>"]
description = "A duplicate of trace normalization implemented in the agent in https://github.com/DataDog/datadog-agent/blob/main/pkg/trace/traceutil/normalize.go"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0"
datadog-trace-protobuf = { path = "../trace-protobuf" }

[dev-dependencies]
rand = "0.8.5"
duplicate = "0.4.1"
