[package]
name = "datadog-trace-normalization"
version = "2.0.0"
authors = ["David Lee <david.lee@datadoghq.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0"
datadog-trace-protobuf = { path = "../trace-protobuf" }

[dev-dependencies]
rand = "0.8.5"
duplicate = "0.4.1"
