[package]
name = "datadog-trace-normalization"
authors = ["David Lee <david.lee@datadoghq.com>"]
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0"
datadog-trace-protobuf = { path = "../trace-protobuf" }

[dev-dependencies]
rand = "0.8.5"
duplicate = "0.4.1"
criterion = "0.5"

[[bench]]
name = "normalization_utils"
harness = false
