# Unless explicitly stated otherwise all files in this repository are licensed under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2021-Present Datadog, Inc.

[package]
name = "ddprof-ffi"
version = "0.6.0-rc.1"
edition = "2018"
license = "Apache-2.0"

[lib]
# LTO is ignored if "lib" is added as crate type
# cf. https://github.com/rust-lang/rust/issues/51009
crate-type = ["staticlib", "cdylib"]

[dependencies]
chrono = "0.4"
ddprof-exporter = { path = "../ddprof-exporter", version = "0.6.0-rc.1" }
ddprof-profiles = { path = "../ddprof-profiles", version = "0.6.0-rc.1" }
libc = "0.2"
hyper = { version = "0.14", default-features = false }
