# Copyright 2021-Present Datadog, Inc. https://www.datadoghq.com/
# SPDX-License-Identifier: Apache-2.0

[package]
name = "datadog-profiling-ffi"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
# LTO is ignored if "lib" is added as crate type
# cf. https://github.com/rust-lang/rust/issues/51009
crate-type = ["staticlib", "cdylib"]
bench = false

[features]
default = []
cbindgen = ["build_common/cbindgen", "ddcommon-ffi/cbindgen"]
ddtelemetry-ffi = ["dep:ddtelemetry-ffi"]
symbolizer = ["symbolizer-ffi"]
data-pipeline-ffi = ["dep:data-pipeline-ffi"]
crashtracker-ffi = ["dep:datadog-crashtracker-ffi"]
# Enables the in-process collection of crash-info
crashtracker-collector = ["crashtracker-ffi", "datadog-crashtracker-ffi/collector"]
# Enables the use of this library to receiver crash-info from a suitable collector
crashtracker-receiver = ["crashtracker-ffi", "datadog-crashtracker-ffi/receiver"]
demangler = ["crashtracker-ffi", "datadog-crashtracker-ffi/demangler"]

[build-dependencies]
build_common = { path = "../build-common" }

[dependencies]
anyhow = "1.0"
datadog-crashtracker-ffi = { path = "../crashtracker-ffi", default-features = false, optional = true}
datadog-profiling = { path = "../profiling" }
data-pipeline-ffi = { path = "../data-pipeline-ffi", default-features = false, optional = true }
ddcommon = { path = "../ddcommon"}
ddcommon-ffi = { path = "../ddcommon-ffi", default-features = false }
ddtelemetry-ffi = { path = "../ddtelemetry-ffi", default-features = false, optional = true, features = ["expanded_builder_macros"] }
futures = { version = "0.3", default-features = false }
libc = "0.2"
serde_json = { version = "1.0" }
symbolizer-ffi = { path = "../symbolizer-ffi", optional = true, default-features = false }
symbolic-demangle = { version = "12.8.0", default-features = false, features = ["rust", "cpp", "msvc"] }
symbolic-common = "12.8.0"
tokio-util = "0.7.1"

[dev-dependencies]
http-body-util = "0.1"
