# Copyright 2021-Present Datadog, Inc. https://www.datadoghq.com/
# SPDX-License-Identifier: Apache-2.0

language = "C"
cpp_compat = true
tab_width = 2
header = """// Copyright 2021-Present Datadog, Inc. https://www.datadoghq.com/
// SPDX-License-Identifier: Apache-2.0
"""
include_guard = "DDOG_PROFILING_H"
style = "both"
pragma_once = true

no_includes = true
sys_includes = ["stdbool.h", "stddef.h", "stdint.h"]
includes = ["common.h"]

[export]
prefix = "ddog_prof_"
renaming_overrides_prefixing = true

[export.rename]
"ByteSlice" = "ddog_ByteSlice"
"CancellationToken" = "ddog_CancellationToken"
"CharSlice" = "ddog_CharSlice"
"Endpoint" = "ddog_Endpoint"
"Error" = "ddog_Error"
"HttpStatus" = "ddog_HttpStatus"
"Slice_CChar" = "ddog_Slice_CChar"
"Slice_I64" = "ddog_Slice_I64"
"Slice_U8" = "ddog_Slice_U8"
"Tag" = "ddog_Tag"
"Timespec" = "ddog_Timespec"
"Vec_Tag" = "ddog_Vec_Tag"
"Vec_U8" = "ddog_Vec_U8"

"ProfilingEndpoint" = "ddog_prof_Endpoint"
"ExporterNewResult" = "ddog_prof_Exporter_NewResult"
"File" = "ddog_prof_Exporter_File"
"ProfileExporter" = "ddog_prof_Exporter"
"ProfileNewResult" = "ddog_prof_Profile_NewResult"
"ProfileResult" = "ddog_prof_Profile_Result"
"Request" = "ddog_prof_Exporter_Request"
"RequestBuildResult" = "ddog_prof_Exporter_Request_BuildResult"
"SendResult" = "ddog_prof_Exporter_SendResult"
"SerializeResult" = "ddog_prof_Profile_SerializeResult"
"Slice_File" = "ddog_prof_Exporter_Slice_File"
"ManagedStringStorage" = "ddog_prof_ManagedStringStorage"
"ManagedStringId" = "ddog_prof_ManagedStringId"
"StringWrapper" = "ddog_StringWrapper"
"StringWrapperResult" = "ddog_StringWrapperResult"
"VoidResult" = "ddog_VoidResult"

"Slice_GenerationalIdLabelId" = "ddog_prof_Slice_LabelId"

"GenerationalId_FunctionId" = "ddog_prof_FunctionId"
"Result_GenerationalIdFunctionId" = "ddog_prof_FunctionId_Result"
"FunctionId" = "OpaqueFunctionId"

"GenerationalId_LabelId" = "ddog_prof_LabelId"
"Result_GenerationalIdLabelId" = "ddog_prof_LabelId_Result"
"LabelId" = "OpaqueLabelId"

"GenerationalId_LabelSetId" = "ddog_prof_LabelSetId"
"Result_GenerationalIdLabelSetId" = "ddog_prof_LabelSetId_Result"
"LabelSetId" = "OpaqueLabelSetId"

"GenerationalId_LocationId" = "ddog_prof_LocationId"
"Result_GenerationalIdLocationId" = "ddog_prof_LocationId_Result"
"LocationId" = "OpaqueLocationId"

"GenerationalId_MappingId" = "ddog_prof_MappingId"
"Result_GenerationalIdMappingId" = "ddog_prof_MappingId_Result"
"MappingId" = "OpaqueMappingId"

"GenerationalId_StackTraceId" = "ddog_prof_StackTraceId"
"Result_GenerationalIdStackTraceId" = "ddog_prof_StackTraceId_Result"
"StackTraceId" = "OpaqueStackTraceId"

"GenerationalId_StringId" = "ddog_prof_StringId"
"Result_GenerationalIdStringId" = "ddog_prof_StringId_Result"
"StringId" = "OpaqueStringId"

[export.mangle]
rename_types = "PascalCase"

[enum]
prefix_with_name = true
rename_variants = "ScreamingSnakeCase"

[fn]
must_use = "DDOG_CHECK_RETURN"

[parse]
parse_deps = true
include = ["ddcommon", "ddcommon-ffi", "datadog-profiling", "datadog-crashtracker", "ux"]

