// Copyright 2021-Present Datadog, Inc. https://www.datadoghq.com/
// SPDX-License-Identifier: Apache-2.0

// This file is @generated by prost-build from `proto/intake_v3.proto`. Do not edit it directly:
// regenerate it with `cargo build -p libdd-metrics-v3 --features generate-protobuf` after
// changing the vendored .proto file.
#![allow(dead_code, clippy::all, clippy::pedantic, clippy::nursery)]

// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Payload {
    #[prost(message, optional, tag = "2")]
    pub metadata: ::core::option::Option<Metadata>,
    #[prost(message, optional, tag = "3")]
    pub metric_data: ::core::option::Option<MetricData>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Metadata {
    #[prost(string, repeated, tag = "1")]
    pub tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// even number of elements, \[Type, Name\] pairs
    #[prost(string, repeated, tag = "2")]
    pub resources: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MetricData {
    /// Dictionaries
    /// All dictionary indexes are base-1, zero implicitly represents an empty value.
    ///
    /// varint length + value
    #[prost(bytes = "vec", tag = "1")]
    pub dict_name_str: ::prost::alloc::vec::Vec<u8>,
    /// varint length + value
    #[prost(bytes = "vec", tag = "2")]
    pub dict_tag_str: ::prost::alloc::vec::Vec<u8>,
    /// length, delta encoded set of indexes into dictTagsStr
    #[prost(sint64, repeated, tag = "3")]
    pub dict_tagsets: ::prost::alloc::vec::Vec<i64>,
    /// varint length + value
    #[prost(bytes = "vec", tag = "4")]
    pub dict_resource_str: ::prost::alloc::vec::Vec<u8>,
    /// number of elements in Type and Name arrays
    #[prost(int64, repeated, tag = "5")]
    pub dict_resource_len: ::prost::alloc::vec::Vec<i64>,
    /// delta encoded set of indexes into dictResourceStr
    #[prost(sint64, repeated, tag = "6")]
    pub dict_resource_type: ::prost::alloc::vec::Vec<i64>,
    /// delta encoded set of indexes into dictResourceStr
    #[prost(sint64, repeated, tag = "7")]
    pub dict_resource_name: ::prost::alloc::vec::Vec<i64>,
    /// varint length + value
    #[prost(bytes = "vec", tag = "8")]
    pub dict_source_type_name: ::prost::alloc::vec::Vec<u8>,
    /// (product, category, service) tuples
    #[prost(int32, repeated, tag = "9")]
    pub dict_origin_info: ::prost::alloc::vec::Vec<i32>,
    /// varint length + value
    #[prost(bytes = "vec", tag = "25")]
    pub dict_unit_str: ::prost::alloc::vec::Vec<u8>,
    /// One entry per time series
    ///
    /// type = metricType | valueType | metricFlags
    #[prost(uint64, repeated, tag = "10")]
    pub types: ::prost::alloc::vec::Vec<u64>,
    /// index into dictNameStr, entire array is delta encoded
    #[prost(sint64, repeated, tag = "11")]
    pub name_refs: ::prost::alloc::vec::Vec<i64>,
    /// index into dictTagsets, entire array is delta encoded
    #[prost(sint64, repeated, tag = "12")]
    pub tagset_refs: ::prost::alloc::vec::Vec<i64>,
    /// index into dictResourceLen, entire array is delta encoded
    #[prost(sint64, repeated, tag = "13")]
    pub resources_refs: ::prost::alloc::vec::Vec<i64>,
    #[prost(uint64, repeated, tag = "14")]
    pub intervals: ::prost::alloc::vec::Vec<u64>,
    #[prost(uint64, repeated, tag = "15")]
    pub num_points: ::prost::alloc::vec::Vec<u64>,
    /// index into dictSourceTypeName, entire array is delta encoded
    #[prost(sint64, repeated, tag = "23")]
    pub source_type_name_refs: ::prost::alloc::vec::Vec<i64>,
    /// index into dictOriginInfo, entire array is delta encoded
    #[prost(sint64, repeated, tag = "24")]
    pub origin_info_refs: ::prost::alloc::vec::Vec<i64>,
    /// index into dictUnitStr, value present if flagHasUnit is set, entire array is delta encoded
    #[prost(sint64, repeated, tag = "26")]
    pub unit_refs: ::prost::alloc::vec::Vec<i64>,
    /// each metric has numPoints values in this section
    ///
    /// entire array delta encoded
    #[prost(sint64, repeated, tag = "16")]
    pub timestamps: ::prost::alloc::vec::Vec<i64>,
    /// or
    #[prost(sint64, repeated, tag = "17")]
    pub vals_sint64: ::prost::alloc::vec::Vec<i64>,
    /// or
    #[prost(float, repeated, tag = "18")]
    pub vals_float32: ::prost::alloc::vec::Vec<f32>,
    /// based on valueType
    #[prost(double, repeated, tag = "19")]
    pub vals_float64: ::prost::alloc::vec::Vec<f64>,
    #[prost(uint64, repeated, tag = "20")]
    pub sketch_num_bins: ::prost::alloc::vec::Vec<u64>,
    /// per-metric sequence is delta encoded
    #[prost(sint32, repeated, tag = "21")]
    pub sketch_bin_keys: ::prost::alloc::vec::Vec<i32>,
    /// sketch summary Sum, Min, Max are encoded as three consecutive elements in one of vals using valueType
    /// sketch summary Cnt is always encoded in valInt64
    /// sketch summary Avg is reconstructed as Sum/Cnt in the intake
    #[prost(uint32, repeated, tag = "22")]
    pub sketch_bin_cnts: ::prost::alloc::vec::Vec<u32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Response {
    #[prost(string, tag = "1")]
    pub error: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MetricType {
    Unused = 0,
    Count = 1,
    Rate = 2,
    Gauge = 3,
    Sketch = 4,
}
impl MetricType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unused => "UNUSED",
            Self::Count => "Count",
            Self::Rate => "Rate",
            Self::Gauge => "Gauge",
            Self::Sketch => "Sketch",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNUSED" => Some(Self::Unused),
            "Count" => Some(Self::Count),
            "Rate" => Some(Self::Rate),
            "Gauge" => Some(Self::Gauge),
            "Sketch" => Some(Self::Sketch),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ValueType {
    /// value is zero, not stored explicitly
    Zero = 0,
    /// value is stored in valsSint64
    Sint64 = 16,
    /// value is stored in valsFloat32
    Float32 = 32,
    /// value is stored in valsFloat64
    Float64 = 48,
}
impl ValueType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Zero => "Zero",
            Self::Sint64 => "Sint64",
            Self::Float32 => "Float32",
            Self::Float64 => "Float64",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Zero" => Some(Self::Zero),
            "Sint64" => Some(Self::Sint64),
            "Float32" => Some(Self::Float32),
            "Float64" => Some(Self::Float64),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MetricFlags {
    FlagNone = 0,
    /// metric should not be indexed (equivalent to origin metric type == agent_hidden in v2)
    FlagNoIndex = 256,
    /// timeseries has a unit in the unitRefs column
    FlagHasUnit = 512,
}
impl MetricFlags {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::FlagNone => "flagNone",
            Self::FlagNoIndex => "flagNoIndex",
            Self::FlagHasUnit => "flagHasUnit",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "flagNone" => Some(Self::FlagNone),
            "flagNoIndex" => Some(Self::FlagNoIndex),
            "flagHasUnit" => Some(Self::FlagHasUnit),
            _ => None,
        }
    }
}
