[package]
name = "ddcommon-ffi"
version = "0.7.0-rc.1"
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ddcommon = { path = "../ddcommon", version = "0.7.0-rc.1" }
anyhow = "1.0"
