// Copyright 2026-Present Datadog, Inc. https://www.datadoghq.com/
// SPDX-License-Identifier: Apache-2.0

//! Verify that the TLSDESC access to `otel_thread_ctx_v1` emitted by our inline assembly
//! ([`libdd_otel_thread_ctx::linux::tls_slot`]) is byte-for-byte identical to what a reference C
//! compiler emits for a `global-dynamic` TLSDESC access.
//!
//! Rather than compiling a C reference at test time, which requires to control precisely the
//! toolchain for reproducibility, and doing a instruction per instruction comparison, we compare a
//! SHA-256 hash of our sequence against a
//! hardcoded "golden" hash generated once instead.
//!
//! The golden hash is generated once outside of tests from a pinned toolchain and a C shim (see
//! [`EXPECTED_TLSDESC_HASH_X86_64`] / [`EXPECTED_TLSDESC_HASH_AARCH64`] via the `gen_tls_shim_hash`
//! binary). This ensures we have the exact same assembly than the one generated by the pinned
//! toolchain. We can update this hash if in the future the sequence generated by clang/gcc change
//! and we want to match the newer versions.
//!
//! We inspect the `staticlib` artifact (unlinked, so the relocations are still present) rather than
//! the relaxed `cdylib`. Library artifact paths are derived at runtime from the test executable
//! location.

#![cfg(all(
    target_os = "linux",
    any(target_arch = "x86_64", target_arch = "aarch64")
))]

use libdd_otel_thread_ctx::test_utils::artifacts::{artifact_path, check_readable};
use libdd_otel_thread_ctx::test_utils::tls_shim_window::{windows_in_archive, Arch, SYMBOL};

/// Golden SHA-256 of the full x86-64 TLSDESC sequence (`lea …@tlsdesc` / `call …@tlscall` /
/// `add %fs:0x0, %rax`), generated by the `gen_tls_shim_hash` binary. See [`regenerate_hint`].
const EXPECTED_TLSDESC_HASH_X86_64: &str =
    "5b38b6b2a151997785463a5d9d2b1f1cb9027660ea37f2aafe94867508cedc66";

/// Golden SHA-256 of the full aarch64 TLSDESC sequence (`adrp`/`ldr`/`add`/`blr` followed by the
/// thread-pointer computation `mrs x8, tpidr_el0` / `add x0, x8, x0`), generated by the
/// `gen_tls_shim_hash` binary. See [`regenerate_hint`].
const EXPECTED_TLSDESC_HASH_AARCH64: &str =
    "f8adc6415409a726b51332a2c36931de9d3537dc33705c4a4aa160268e40ca97";

fn expected_hash(arch: Arch) -> &'static str {
    match arch {
        Arch::X86_64 => EXPECTED_TLSDESC_HASH_X86_64,
        Arch::Aarch64 => EXPECTED_TLSDESC_HASH_AARCH64,
    }
}

/// Explains, for a failure message, how the golden hash is produced and how to refresh it.
fn regenerate_hint() -> String {
    "The golden hash is the SHA-256 of the TLSDESC access sequence a reference C compiler emits for \
     a small TLS shim generated by the `gen_tls_shim_hash` binary. \
     If you changed the inline assembly in `libdd_otel_thread_ctx::linux::tls_slot` (or the pinned \
     toolchain) on purpose, see `gen_tls_shim_hash.rs` for instructions to re-run the \
     generator and update `EXPECTED_TLSDESC_HASH_*` in this file. Otherwise, the sequence our \
     assembly produces has drifted from what some compiler emits (and from what the linker expects \
     for TLS relaxation): run the generator and diff its `bytes:` line against the `actual bytes` \
     above to see which instruction differs."
        .to_owned()
}

#[test]
#[cfg_attr(miri, ignore)]
fn tlsdesc_inline_assembly_matches_reference_hash() {
    let staticlib = artifact_path("liblibdd_otel_thread_ctx_ffi.a");
    check_readable(&staticlib);

    let windows = windows_in_archive(&staticlib);
    assert!(
        !windows.is_empty(),
        "expected at least one Rust inline-asm TLSDESC access for {SYMBOL} in {}",
        staticlib.display()
    );

    for window in windows {
        let expected = expected_hash(window.arch);
        let actual = window.hash_hex();
        assert_eq!(
            actual,
            expected,
            "\nTLSDESC sequence hash mismatch for {SYMBOL} in {}\n  \
             arch:          {:?}\n  \
             actual bytes:  {}\n  \
             actual hash:   {}\n  \
             expected hash: {}\n\n{}",
            window.label,
            window.arch,
            window.hex_dump(),
            actual,
            expected,
            regenerate_hint(),
        );
    }
}
