[package]
name = "trace-utils-benches"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license.workspace = true
autobenches = false

[dependencies]
datadog-trace-utils = { path = "../../trace-utils" }

[dev-dependencies]
anyhow = "~1.0.82"
clap = { workspace = true }
criterion = { workspace = true }
rmp-serde = "~1.3.0"
serde_json = "~1.0.120"

[lib]
bench = false

[[bench]]
name = "main"
harness = false
