[package]
name = "datadog-appsec"
version = "0.1.0"
edition = "2021"
description = "An empty Datadog crate"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
