// Copyright 2023-Present Datadog, Inc. https://www.datadoghq.com/
// SPDX-License-Identifier: Apache-2.0

// This file is @generated by prost-build.
pub mod opentelemetry {
    pub mod proto {
        pub mod common {
            pub mod v1 {
                include!("opentelemetry.proto.common.v1.rs");
            }
        }
        pub mod resource {
            pub mod v1 {
                include!("opentelemetry.proto.resource.v1.rs");
            }
        }
    }
}
pub mod pb {
    include!("pb.rs");
    pub mod idx {
        include!("pb.idx.rs");
    }
}
pub mod remoteconfig {
    include!("remoteconfig.rs");
}
