[package]
name = "datadog-profiling-replayer"
authors = ["Levi Morrison <levi.morrison@datadoghq.com>"]
description = "Takes a pprof file and 'replays' it using libdatadog commands."
version = "3.0.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0"
clap = { version = "4.3.21", features = ["cargo", "color", "derive"] }
datadog-profiling = { path = "../profiling"}
prost = "0.11"
sysinfo = {version = "0.29.8", default-features = false}
