[package]
name = "datadog-profiling-replayer"
authors = ["Levi Morrison <levi.morrison@datadoghq.com>"]
description = "Takes a pprof file and 'replays' it using libdatadog commands."
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0"
clap = { version = "4.3.21", features = ["cargo", "color", "derive"] }
datadog-profiling = { path = "../profiling"}
prost = { git = "https://github.com/morrisonlevi/prost.git", rev = "6f47e2eb8bce2451cad33e872ea32998c894e7d4" }
sysinfo = {version = "0.29.8", default-features = false}
