services:
  runner:
    image: "us-central1-docker.pkg.dev/molten-verve-216720/datadog-repository/datarace-example:v02"
    build:
      context: .
      dockerfile: Dockerfile.runner
    container_name: datarace-example
