[package]
name = "libdd-ffe"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true
license.workspace = true
autobenches = false
homepage = "https://github.com/DataDog/libdatadog/tree/main/libdd-ffe"
repository = "https://github.com/DataDog/libdatadog/tree/main/libdd-ffe"
description = "Feature Flagging and Experimentation"

[lib]
bench = false

[dependencies]
libdd-remote-config = { version = "2.0.0", path = "../libdd-remote-config", default-features = false, optional = true }
faststr = { version = "0.2.23", default-features = false, features = ["serde"] }
serde = { workspace = true, features = ["derive", "rc"] }
serde_json = { workspace = true, features = ["std", "raw_value"] }
chrono = { workspace = true, features = ["now", "serde"] }
derive_more = { version = "2.0.0", default-features = false, features = ["from", "into"] }
log = { version = "0.4.21", default-features = false, features = ["kv", "kv_serde"] }
md5 = { version = "0.7.0", default-features = false }
libdd-common = { version = "5.1.0", path = "../libdd-common", default-features = false, features = ["require-regex-full"] }
semver = "1.0"
thiserror = { version = "2.0.3", default-features = false }
lru = { version = "0.16.3", optional = true }
libdd-trace-protobuf = { version = "4.0.0", path = "../libdd-trace-protobuf", optional = true }
prost = { version = "0.14.1", optional = true }
pyo3 = { version = "0.28", optional = true, default-features = false, features = ["macros"] }

[features]
default = ["remote-config"]
exposure-events = ["dep:lru"]
evaluation-metrics = ["dep:libdd-trace-protobuf", "dep:prost"]
pyo3 = ["dep:pyo3"]
remote-config = ["dep:libdd-remote-config"]
