[package]
name = "libdd-ffe"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true
license.workspace = true
autobenches = false
publish = false

[lib]
bench = false

[dependencies]
faststr = { version = "0.2.23", default-features = false, features = ["serde"] }
serde = { version = "1.0", default-features = false, features = ["derive", "rc"] }
serde_json = { version = "1.0", default-features = false, features = ["std"] }
chrono = { version = "0.4.38", default-features = false, features = ["now", "serde"] }
derive_more = { version = "2.0.0", default-features = false, features = ["from", "into"] }
log = { version = "0.4.21", default-features = false, features = ["kv", "kv_serde"] }
md5 = { version = "0.7.0", default-features = false }
regex = "1.10.4"
serde-bool = { version = "0.1.3", default-features = false }
serde_with = { version = "3.11.0", default-features = false, features = ["base64", "hex", "macros"] }
thiserror = "2.0.3"
url = "2.5.0"

[dev-dependencies]
env_logger = "0.10"
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "ffe-eval"
harness = false
path = "benches/eval.rs"
