// Copyright 2026-Present Datadog, Inc. https://www.datadoghq.com/
// SPDX-License-Identifier: Apache-2.0

//! Verify that the TLSDESC access to `otel_thread_ctx_v1` emitted by our inline assembly
//! ([`libdd_otel_thread_ctx::linux::tls_slot`]) is byte-for-byte identical to what a reference C
//! compiler emits for a `global-dynamic` TLSDESC access.
//!
//! Rather than compiling a C reference at test time, which requires to control precisely the
//! toolchain for reproducibility, we compare our sequence's raw bytes against a hardcoded "golden"
//! byte sequence generated once instead (the sequence is small — well under the size of a SHA-256
//! hash — so there's no need to hash it).
//!
//! The golden bytes are generated once outside of tests from a pinned toolchain and a C shim (see
//! [`EXPECTED_TLSDESC_BYTES_X86_64`] / [`EXPECTED_TLSDESC_BYTES_AARCH64`] via the
//! `gen_tls_shim_bytes` binary). This ensures we have the exact same assembly than the one
//! generated by the pinned toolchain. We can update these bytes if in the future the sequence
//! generated by clang/gcc change and we want to match the newer versions.
//!
//! We inspect this crate's own `rlib` artifact (unlinked, so the relocations are still present)
//! rather than the relaxed `cdylib` built by `libdd-otel-thread-ctx-ffi`. Library artifact paths
//! are derived at runtime from the test executable location.

#![cfg(all(
    target_os = "linux",
    any(target_arch = "x86_64", target_arch = "aarch64")
))]

use libdd_otel_thread_ctx::test_utils::artifacts::rlib_path;
use libdd_otel_thread_ctx::test_utils::tls_shim_window::{windows_in_archive, Arch, SYMBOL};

/// Golden bytes of the full x86-64 TLSDESC sequence, generated by the `gen_tls_shim_bytes` binary.
/// See [`regenerate_hint`].
const EXPECTED_TLSDESC_BYTES_X86_64: &[u8] = &[
    0x48, 0x8d, 0x05, 0x00, 0x00, 0x00, 0x00, 0xff, 0x10, 0x64, 0x48, 0x03, 0x04, 0x25, 0x00, 0x00,
    0x00, 0x00,
];

/// Golden bytes of the full aarch64 TLSDESC sequence, generated by the `gen_tls_shim_bytes` binary.
/// See [`regenerate_hint`].
const EXPECTED_TLSDESC_BYTES_AARCH64: &[u8] = &[
    0x00, 0x00, 0x00, 0x90, 0x01, 0x00, 0x40, 0xf9, 0x00, 0x00, 0x00, 0x91, 0x20, 0x00, 0x3f, 0xd6,
    0x48, 0xd0, 0x3b, 0xd5, 0x00, 0x01, 0x00, 0x8b,
];

const fn expected_bytes(arch: Arch) -> &'static [u8] {
    match arch {
        Arch::X86_64 => EXPECTED_TLSDESC_BYTES_X86_64,
        Arch::Aarch64 => EXPECTED_TLSDESC_BYTES_AARCH64,
    }
}

/// Explains, for a failure message, how the golden bytes are produced and how to refresh them.
fn regenerate_hint() -> String {
    "The golden bytes are the TLSDESC access sequence a reference C compiler emits for a small TLS \
     shim generated by the `gen_tls_shim_bytes` binary. \
     If you changed the inline assembly in `libdd_otel_thread_ctx::linux::tls_slot` (or the pinned \
     toolchain) on purpose, see `gen_tls_shim_bytes.rs` for instructions to re-run the \
     generator and update `EXPECTED_TLSDESC_BYTES_*` in this file. Otherwise, the sequence our \
     assembly produces has drifted from what some compiler emits (and from what the linker expects \
     for TLS relaxation): run the generator and diff its `bytes:` line against the `actual bytes` \
     above to see which instruction differs."
        .to_owned()
}

#[test]
#[cfg_attr(miri, ignore)]
fn tlsdesc_inline_assembly_matches_reference_bytes() {
    let rlib = rlib_path("libdd_otel_thread_ctx");

    let windows = windows_in_archive(&rlib);
    assert!(
        !windows.is_empty(),
        "expected at least one Rust inline-asm TLSDESC access for {SYMBOL} in {}",
        rlib.display()
    );

    for window in windows {
        let expected = expected_bytes(window.arch);
        assert_eq!(
            window.bytes,
            expected,
            "\nTLSDESC sequence mismatch for {SYMBOL} in {}\n  \
             arch:           {:?}\n  \
             actual bytes:   {}\n  \
             expected bytes: {}\n\n{}",
            window.label,
            window.arch,
            window.hex_dump(),
            expected
                .iter()
                .map(|b| format!("{b:02x}"))
                .collect::<String>(),
            regenerate_hint(),
        );
    }
}
