// Copyright 2025-Present Datadog, Inc. https://www.datadoghq.com/
// SPDX-License-Identifier: Apache-2.0

//! Rust bindings for the libdd-heap-sampler C library.
//!
//! FFI declarations and `#[repr(C)]` struct mirrors are generated by
//! `bindgen` from the public headers under `include/datadog/heap/` at
//! build time; see `build.rs`. All items are re-exported at the crate
//! root.
//!
//! The `static inline __attribute__((always_inline))` fast-path helpers in
//! the headers have no linker symbol, so bindgen's `wrap_static_fns`
//! emits a C shim for each - the shim's body is the static-inline
//! inlined at its one call site. The shim's link-symbol is
//! `<fn>__extern`, but bindgen exposes the Rust fn under the natural C
//! name via `#[link_name]`, so callers write `dd_allocation_requested(…)`
//! the same way they would in C.

// USDT/SystemTap is Linux-only; on every other target the crate is an empty
// rlib. macOS is `unix` too, so we gate on target_os = "linux" specifically.
#[cfg(target_os = "linux")]
#[allow(
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals,
    dead_code
)]
mod sys {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

#[cfg(target_os = "linux")]
pub use sys::*;

// Tests exercise the C/FFI sampler primitives directly; miri can't
// execute foreign code, so skip the whole module under miri.
#[cfg(all(test, target_os = "linux", not(miri)))]
mod tests {
    use super::*;
    use core::ffi::c_void;

    #[test]
    fn alloc_req_layout_matches_c() {
        assert_eq!(core::mem::size_of::<dd_alloc_req_t>(), 32);
        assert_eq!(core::mem::align_of::<dd_alloc_req_t>(), 8);
    }

    #[test]
    fn tl_state_layout_matches_c() {
        assert_eq!(core::mem::size_of::<dd_tl_state_t>(), 24);
        assert_eq!(core::mem::align_of::<dd_tl_state_t>(), 8);
    }

    #[test]
    fn requested_initializes_tls_on_first_use() {
        std::thread::spawn(|| unsafe {
            assert!(
                dd_tl_state_get().is_null(),
                "fresh thread should start without sampler TLS"
            );
            let req = dd_allocation_requested(1, 1);
            assert_eq!(req.size, 1);
            assert_eq!(req.weight, 0);
            assert!(
                !dd_tl_state_get().is_null(),
                "request should initialize sampler TLS"
            );
        })
        .join()
        .unwrap();
    }

    #[test]
    fn created_is_passthrough_when_weight_zero() {
        unsafe {
            let fake = 0xdead_beef_usize as *mut c_void;
            let req = dd_alloc_req_t {
                size: 64,
                user_size: 64,
                alignment: 8,
                weight: 0,
            };
            assert_eq!(dd_allocation_created(fake, req), fake);
        }
    }

    #[test]
    fn zero_sampling_interval_disables_sampling() {
        let mut tl = dd_tl_state_t {
            sampling_interval: 0,
            remaining_bytes: 0,
            remaining_bytes_initialized: true,
            initialized: true,
            reentry_guard: false,
            rng: 1,
        };

        let req = unsafe { dd_allocation_requested_slow(&mut tl, 64, 8) };

        assert_eq!(req.size, 64);
        assert_eq!(req.user_size, 64);
        assert_eq!(req.alignment, 8);
        assert_eq!(req.weight, 0);
        assert!(!tl.reentry_guard);
    }

    #[test]
    fn freed_unsampled_returns_inputs_unchanged() {
        // The C side now reads 8 bytes at ptr-16 looking for DD_MAGIC,
        // so we need a real buffer underneath. Zero contents won't match,
        // so the function returns inputs verbatim.
        let mut buf = vec![0u8; 128];
        let ptr = unsafe { buf.as_mut_ptr().add(16) } as *mut c_void;
        unsafe {
            let freed = dd_allocation_freed(ptr, 64, 8);
            assert_eq!(freed.ptr, ptr);
            assert_eq!(freed.size, 64);
        }
    }

    #[cfg(target_arch = "x86_64")]
    #[test]
    fn sample_flag_check_fast_rejects_invalid_offset() {
        const MAGIC: u64 = 0xfab1eddec0dedca7;
        const HEADER_BYTES: usize = 16;

        let mut buf = vec![0u8; 8192];
        let base = buf.as_mut_ptr() as usize;
        let user_addr = (base + 128 + 4095) & !4095;
        let user_addr = user_addr + 64;
        assert!(user_addr + 64 <= base + buf.len());

        let header = user_addr - HEADER_BYTES;
        let header_idx = header - base;
        buf[header_idx..header_idx + 8].copy_from_slice(&MAGIC.to_ne_bytes());
        // Too small to have been produced by x86_apply().
        buf[header_idx + 8..header_idx + 16].copy_from_slice(&8u64.to_ne_bytes());

        let mut raw = core::ptr::null_mut();
        let sampled = unsafe { dd_sample_flag_check(user_addr as *mut c_void, &mut raw) };

        assert!(!sampled);
        assert!(raw.is_null());
        assert_eq!(&buf[header_idx..header_idx + 8], &MAGIC.to_ne_bytes());
    }

    #[cfg(target_arch = "x86_64")]
    #[test]
    fn freed_slow_size_matches_requested_bump_formula() {
        const HEADER_BYTES: usize = 16;

        fn requested_bumped_size(user_size: usize, alignment: usize) -> usize {
            let base = alignment.max(HEADER_BYTES);
            let reserve = 2 * base;
            let bumped = user_size + reserve;
            if alignment > 1 {
                let mask = alignment - 1;
                (bumped + mask) & !mask
            } else {
                bumped
            }
        }

        let user_size = 100;
        let alignment = 16;
        let base = alignment.max(HEADER_BYTES);
        let raw = 0x100000usize as *mut c_void;
        let ptr = (0x100000usize + base) as *mut c_void;

        let freed = unsafe { dd_allocation_freed_slow(ptr, raw, user_size, alignment) };

        assert_eq!(freed.ptr, raw);
        assert_eq!(freed.size, requested_bumped_size(user_size, alignment));
    }

    #[test]
    fn tl_state_init_then_get_returns_same_non_null() {
        std::thread::spawn(|| unsafe {
            let initialized = dd_tl_state_init();
            assert!(!initialized.is_null(), "init returned NULL on fresh thread");
            let got = dd_tl_state_get();
            assert_eq!(initialized, got);
            assert_eq!((*got).sampling_interval, 512 * 1024);
        })
        .join()
        .unwrap();
    }
}
