// Copyright 2025-Present Datadog, Inc. https://www.datadoghq.com/
// SPDX-License-Identifier: Apache-2.0

//! Rust bindings for the libdd-heap-sampler C library.
//!
//! FFI declarations and `#[repr(C)]` struct mirrors are generated by
//! `bindgen` from the public headers under `include/datadog/heap/` at
//! build time; see `build.rs`. All items are re-exported at the crate
//! root.
//!
//! The `static inline __attribute__((always_inline))` fast-path helpers in
//! the headers have no linker symbol, so bindgen's `wrap_static_fns`
//! emits C shim for each - the shim's body is the static-inline
//! inlined at its one call site. The shim's link-symbol is
//! `<fn>__extern`, but bindgen exposes the Rust fn under the natural C
//! name via `#[link_name]`, so callers write `dd_allocation_requested(…)`
//! the same way they would in C.
//!

#[cfg(unix)]
#[allow(non_camel_case_types, non_snake_case, non_upper_case_globals, dead_code)]
mod sys {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

#[cfg(unix)]
pub use sys::*;

#[cfg(all(test, unix))]
mod tests {
    use super::*;
    use core::ffi::c_void;

    #[test]
    fn alloc_req_layout_matches_c() {
        assert_eq!(core::mem::size_of::<dd_alloc_req_t>(), 16);
        assert_eq!(core::mem::align_of::<dd_alloc_req_t>(), 8);
    }

    #[test]
    fn tl_state_layout_matches_c() {
        assert_eq!(core::mem::size_of::<dd_tl_state_t>(), 24);
        assert_eq!(core::mem::align_of::<dd_tl_state_t>(), 8);
    }

    #[test]
    fn requested_is_unsampled_when_tl_null() {
        unsafe {
            let req = dd_allocation_requested(1024, 8);
            assert_eq!(req.size, 1024);
            assert_eq!(req.weight, 0);
        }
    }

    #[test]
    fn created_is_passthrough_when_weight_zero() {
        unsafe {
            let fake = 0xdead_beef_usize as *mut c_void;
            let req = dd_alloc_req_t {
                size: 64,
                weight: 0,
            };
            assert_eq!(dd_allocation_created(fake, req), fake);
        }
    }

    #[test]
    fn freed_stub_returns_input_size() {
        unsafe {
            let ptr = 0x1234_usize as *mut c_void;
            assert_eq!(dd_allocation_freed(ptr, 64, 8), 64);
        }
    }

    #[test]
    fn tl_state_init_then_get_returns_same_non_null() {
        std::thread::spawn(|| unsafe {
            let initialized = dd_tl_state_init();
            assert!(!initialized.is_null(), "init returned NULL on fresh thread");
            let got = dd_tl_state_get();
            assert_eq!(initialized, got);
            assert_eq!((*got).sampling_interval, 512 * 1024);
        })
        .join()
        .unwrap();
    }
}
