[package]
name = "libdd-profiling-replayer"
authors = ["Levi Morrison <levi.morrison@datadoghq.com>"]
description = "Takes a pprof file and 'replays' it using libdatadog commands."
edition.workspace = true
version = "1.0.0"
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
anyhow = "1.0"
clap = { version = "4.3.21", features = ["cargo", "color", "derive"] }
datadog-profiling = { path = "../libdd-profiling", package = "libdd-profiling" }
datadog-profiling-protobuf = { path = "../libdd-profiling-protobuf", package = "libdd-profiling-protobuf", features = ["prost_impls"] }
prost = "0.13.5"
sysinfo = { version = "0.29.8", default-features = false }

[[bin]]
name = "datadog-profiling-replayer"
bench = false
path = "src/main.rs"
