# Unless explicitly stated otherwise all files in this repository are licensed under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2021-Present Datadog, Inc.

[package]
name = "ddprof-profiles"
version = "0.6.0-rc.1"
edition = "2018"
build = "build.rs"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "lib"]

[build-dependencies]
prost-build = "0.8"

[dependencies]
indexmap = "1.6"
libc = "0.2"
prost = "0.8"
ux = "0.1"
