# Unless explicitly stated otherwise all files in this repository are licensed under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2021-Present Datadog, Inc.

[package]
edition = "2021"
license = "Apache-2.0"
name = "ddwasm-ffi"
version = "0.7.0-rc.1"

[lib]
crate-type = ["cdylib"]

[dependencies]
ddcommon = {path = "../ddcommon", default-features = false}
sketches-ddsketch = {version = "0.1.2"}
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
anyhow = "1.0"