# Copyright 2021-Present Datadog, Inc. https://www.datadoghq.com/
# SPDX-License-Identifier: Apache-2.0

[package]
name = "ddcommon"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
crate-type = ["lib"]
bench = false

[dependencies]
anyhow = "1.0"
futures = "0.3"
futures-core = { version = "0.3.0", default-features = false }
futures-util = { version = "0.3.0", default-features = false }
hex = "0.4"
hyper = { version = "1.6", features = ["http1", "client"] }
hyper-util = { version = "0.1.10", features = [
    "http1",
    "client",
    "client-legacy",
] }
http = "1.0"
http-body = "1.0"
http-body-util = "0.1"
tower-service = "0.3"
cc = "1.1.31"
log = { version = "0.4" }
pin-project = "1"
rand = "0.8.3"
regex = "1.5"
rmp = "0.8.14"
rmp-serde = "1.3.0"
rustls = { version = "0.23", default-features = false, optional = true }
rustls-native-certs = { version = "0.8", optional = true }
tokio = { version = "1.23", features = ["rt", "macros"] }
tokio-rustls = { version = "0.26", default-features = false, optional = true }
serde = { version = "1.0", features = ["derive"] }
static_assertions = "1.1.0"
libc = "0.2"
const_format = "0.2.34"

[target.'cfg(windows)'.dependencies.windows-sys]
version = "0.52"
features = ["Win32_Foundation", "Win32_System_Performance"]

[target.'cfg(unix)'.dependencies]
hyper-rustls = { version = "0.27", default-features = false, features = [
    "native-tokio",
    "http1",
    "tls12",
    "aws-lc-rs",
], optional = true }
memfd = { version = "0.6" }

[target.'cfg(not(unix))'.dependencies]
hyper-rustls = { version = "0.27", default-features = false, features = [
    "native-tokio",
    "http1",
    "tls12",
    "ring",
], optional = true }

[dev-dependencies]
indexmap = "2.2"
maplit = "1.0"

[features]
default = ["https"]
https = ["tokio-rustls", "rustls", "hyper-rustls", "rustls-native-certs"]
use_webpki_roots = ["hyper-rustls/webpki-roots"]
# Enable this feature to enable stubbing of cgroup
# php directly import this crate and uses functions gated by this feature for their test
cgroup_testing = []
