# Unless explicitly stated otherwise all files in this repository are licensed under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2021-Present Datadog, Inc.

[package]
edition = "2018"
license = "Apache-2.0"
name = "ddcommon"
version = "0.5.0-rc.1"

[lib]
crate-type = ["lib"]

[dependencies]
lazy_static = "1.4"
regex = "1.5"

[dev-dependencies]
maplit = "1.0"
