# Copyright 2021-Present Datadog, Inc. https://www.datadoghq.com/
# SPDX-License-Identifier: Apache-2.0

[package]
name = "ddcommon"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
crate-type = ["lib"]

[features]
default = ["rustls"]
rustls = [ "dep:hyper-rustls", "dep:rustls", "dep:rustls-native-certs", "dep:tokio-rustls" ]
native-tls = [ "dep:hyper-tls" ]

[dependencies]
anyhow = "1.0"
futures = "0.3"
futures-core = { version = "0.3.0", default-features = false }
futures-util = { version = "0.3.0", default-features = false }
hex = "0.4"
http = "0.2"
hyper = { version = "0.14", features = [
    "http1",
    "client",
    "tcp",
    "stream",
], default-features = false }
hyper-rustls = { version = "0.23", default-features = false, features = [
    "native-tokio",
    "http1",
    "tls12",
], optional = true }
hyper-tls = { version = "0.5", default-features = false, optional = true }
lazy_static = "1.4"
log = { version = "0.4" }
pin-project = "1"
regex = "1.5"
rustls = { version = "0.20.4", default-features = false, optional = true}
rustls-native-certs = { version = "0.6", optional = true }
tokio = { version = "1.23", features = ["rt", "macros"] }
tokio-rustls = { version = "0.23", optional = true }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
indexmap = "2.2"
maplit = "1.0"
