[workspace]
resolver = "2"

members = [
    "example-service",
    "tarpc",
    "plugins",
]

[workspace.package]
rust-version = "1.78.0"
edition = "2021"
version = "18.0.0"
license = "Apache-2.0"

[profile.dev]
split-debuginfo = "unpacked"
