[package]
name = "fork_safety_tester"
version = "0.1.0"
edition = "2021"
about = "Utility to create worst possible conditions for calling fork(2)"

[dependencies]
anyhow = { version = "1.0" }
nix = { version = "0.26" }
clap = { version = "4.1", features = ["derive"] }
log = { version = "0.4" }
num_cpus = { version = "1.0" }
spawn_worker = { path= "../../spawn_worker" }

[lib]
crate-type = ["cdylib"]
