# Unless explicitly stated otherwise all files in this repository are licensed under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2021-Present Datadog, Inc.

[package]
name = "ddprof-exporter"
version = "0.6.0"
edition = "2021"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
anyhow = "1.0"
bytes = "1.1"
chrono = "0.4"
futures = "0.3"
futures-core = {version = "0.3.0", default-features = false}
futures-util = {version = "0.3.0", default-features = false}
http = "0.2"
http-body = "0.4"
hyper = {version = "0.14", features = ["client"], default-features = false}
hyper-multipart-rfc7578 = "0.7.0"
libc = "0.2"
mime_guess = {version = "2.0", default-features = false}
percent-encoding = "2.1"
tokio = {version = "1.8", features = ["rt", "macros"]}
tokio-util = "0.7.1"

ddcommon = {path = "../ddcommon"}

[dev-dependencies]
maplit = "1.0"
