# Unless explicitly stated otherwise all files in this repository are licensed under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2021-Present Datadog, Inc.

[package]
name = "ddprof-exporter"
version = "0.2.0"
edition = "2018"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
bytes = "1.0"
chrono = "0.4"
futures = "0.3"
http = "0.2"
libc = "0.2"
reqwest = { version = "0.11", features = ["blocking", "multipart", "rustls-tls"], default-features = false }
tokio = { version = "1.8", features = ["rt"]}
