[package]
name = "libdd-trace-protobuf"
version = "5.0.0"
description = "Protobuf utils for Datadog's traces serialization"
homepage = "https://github.com/DataDog/libdatadog/tree/main/libdd-trace-protobuf"
repository = "https://github.com/DataDog/libdatadog/tree/main/libdd-trace-protobuf"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
bench = false

[dependencies]
bolero = { workspace = true, features = ["std"], optional = true }
prost = { workspace = true, default-features = true }
serde = { workspace = true, features = ["derive"] }
# We tend to prefer the smaller `alloc` feature over `std` for crates that
# expose both, as does `serde_bytes`. However, switching to `alloc` only here
# removes the (required) `Deserialize` implementations of some basic types.
# There might be a way to migrate, but for now, we stay with default-features.
serde_bytes = { workspace = true, default-features = true }

[build-dependencies]
prost-build = { workspace = true, features = ["format"], optional = true }
protoc-bin-vendored = { workspace = true, optional = true }

[features]
generate-protobuf = ["dep:prost-build", "dep:protoc-bin-vendored"]
fuzzing = ["dep:bolero"]

[dev-dependencies]
serde_json.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
