# Copyright 2021-Present Datadog, Inc. https://www.datadoghq.com/
# SPDX-License-Identifier: Apache-2.0

[package]
name = "ddcommon-net1"
rust-version.workspace = true
edition.workspace = true
version.workspace = true
license.workspace = true

[lib]
bench = false

[features]
default = []
use_webpki_roots = ["hyper-rustls/webpki-roots"]

[dependencies]
anyhow = "1"
ddcommon = { path = "../ddcommon" }
futures = "0.3"
futures-core = { version = "0.3.0", default-features = false }
futures-util = { version = "0.3.0", default-features = false }
hex = "0.4"
http = "0.2"
hyper = { version = "0.14", features = ["http1", "client", "tcp", "stream", "backports", "deprecated"], default-features = false }
hyper-util = "0.1"
lazy_static = "1.4"
pin-project = "1"
rustls = { version = "0.23", default-features = false }
rustls-native-certs = { version = "0.7" }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.23", features = ["rt", "macros"] }
tokio-rustls = { version = "0.26", default-features = false }

[target.'cfg(windows)'.dependencies.windows-sys]
version = "0.52"
features = [
    "Win32_Foundation",
    "Win32_System_Performance",
]

[target.'cfg(unix)'.dependencies]
hyper-rustls = { version = "0.27", default-features = false, features = [
    "aws-lc-rs",
    "http1",
    "native-tokio",
    "tls12",
] }

[target.'cfg(not(unix))'.dependencies]
hyper-rustls = { version = "0.27", default-features = false, features = [
    "http1",
    "native-tokio",
    "ring",
    "tls12",
] }
