[package]
name = "libdd-trace-obfuscation"
authors = ["David Lee <david.lee@datadoghq.com>"]
description = "A duplicate of trace obfuscator implemented in the agent and documented in https://docs.datadoghq.com/tracing/configure_data_security/?tab=net#trace-obfuscation"
edition.workspace = true
version = "1.0.0"
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0"
regex = "1"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0"
url = "2.4.0"
percent-encoding = "2.1"
log = "0.4"
datadog-trace-protobuf = { version = "1.0.0", path = "../libdd-trace-protobuf", package = "libdd-trace-protobuf" }
datadog-trace-utils = { version = "1.0.0", path = "../libdd-trace-utils", package = "libdd-trace-utils" }
ddcommon = { version = "1.0.0", path = "../libdd-common", package = "libdd-common" }

[dev-dependencies]
duplicate = "0.4.1"
criterion = { version = "0.5", features = [ "csv_output"] }
datadog-trace-utils = { version = "1.0.0", path = "../libdd-trace-utils", package = "libdd-trace-utils", features = ["test-utils"] }

[lib]
bench = false

[[bench]]
name = "trace_obfuscation"
harness = false
path = "benches/trace_obfuscation.rs"
