[package]
name = "dogstatsd"
rust-version.workspace = true
edition.workspace = true
version.workspace = true
license.workspace = true

[lib]
bench = false

[dependencies]
datadog-protos = { version = "0.1.0", default-features = false, git = "https://github.com/DataDog/saluki/", rev = "c89b58e5784b985819baf11f13f7d35876741222" }
ddsketch-agent = { version = "0.1.0", default-features = false, git = "https://github.com/DataDog/saluki/", rev = "c89b58e5784b985819baf11f13f7d35876741222" }
derive_more = { version = "1.0.0", features = ["display", "into"] }
hashbrown = { version = "0.14.3", default-features = false, features = ["inline-more"] }
protobuf = { version = "3.5.0", default-features = false }
ustr = { version = "1.0.0", default-features = false }
fnv = { version = "1.0.7", default-features = false }
lazy_static = { version = "1.5.0", default-features = false }
reqwest = { version = "0.12.4", features = ["json", "http2", "rustls-tls"], default-features = false }
serde = { version = "1.0.197", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.116", default-features = false, features = ["alloc"] }
thiserror = { version = "1.0.58", default-features = false }
tokio = { version = "1.37.0", default-features = false, features = ["macros", "rt-multi-thread"] }
tokio-util = { version = "0.7.11", default-features = false }
tracing = { version = "0.1.40", default-features = false }
regex = { version = "1.10.6", default-features = false }

[dev-dependencies]
mockito = { version = "1.5.0", default-features = false }
proptest = "1.4.0"
tracing-test = { version = "0.2.5", default-features = false }
