[package]
name = "dogstatsd-client"
rust-version.workspace = true
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
ddcommon = { path = "../ddcommon" }
datadog-trace-protobuf = { path = "../trace-protobuf" }
datadog-trace-utils = { path = "../trace-utils" }
datadog-trace-normalization = { path = "../trace-normalization" }
datadog-ddsketch = { path = "../ddsketch"}
cadence = "1.3.0"
serde = { version = "1.0", features = ["derive", "rc"] }
tracing = { version = "0.1", default-features = false }
anyhow = { version = "1.0" }
hyper = { version = "0.14", features = ["client"], default-features = false }
http = "0.2"
