[package]
name = "libdd-tinybytes"
version= "1.1.3"
description = "Tiny implementation of a bytes::Bytes like type that supports AsRef<[u8]>"
homepage = "https://github.com/DataDog/libdatadog/tree/main/libdd-tinybytes"
repository = "https://github.com/DataDog/libdatadog/tree/main/libdd-tinybytes"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
bench = false

[dev-dependencies]
once_cell = { workspace = true, features = ["std"] }
pretty_assertions = { workspace = true, default-features = true }
proptest = { workspace = true, default-features = true }
test-case.workspace = true
serde_json.workspace = true
libdd-tinybytes = { path = ".", features = ["bytes_string", "serialization"] }
rmp-serde.workspace = true

[dependencies]
serde = { workspace = true, optional = true }
[features]
bytes_string = []
serialization = ["serde"]
