[package]
edition = "2021"
license = "Apache 2.0"
name = "datadog-remote-config"
version = "0.0.1"

[features]
test = ["hyper/server", "hyper-util"]

[dependencies]
anyhow = { version = "1.0" }
ddcommon = { path = "../../ddcommon" }
datadog-dynamic-configuration = { path = "../../dynamic-configuration" }
datadog-trace-protobuf = { path = "../../trace-protobuf" }
datadog-live-debugger = { path = "../datadog-live-debugger" }
hyper = { version = "1.6", features = ["http1", "client"] }
http-body-util = "0.1"
http = "1.0"
base64 = "0.22.1"
sha2 = "0.10"
uuid = { version = "1.7.0", features = ["v4"] }
futures-util = "0.3"
tokio = { version = "1.36.0" }
tokio-util = "0.7.10"
manual_future = "0.1.1"
time = { version = "0.3", features = ["parsing", "serde", "formatting"] }
tracing = { version = "0.1", default-features = false }
serde = "1.0"
serde_json = { version = "1.0", features = ["raw_value"] }

# Test feature
hyper-util = { version = "0.1", features = ["service"], optional = true }

[dev-dependencies]
futures = "0.3"

[lib]
bench = false
