// Copyright 2025-Present Datadog, Inc. https://www.datadoghq.com/
// SPDX-License-Identifier: Apache-2.0

// This module is generated by prost-build from profiles.proto
#[allow(clippy::all)]
pub mod opentelemetry {
    pub mod proto {
        pub mod common {
            pub mod v1 {
                include!(concat!(
                    env!("OUT_DIR"),
                    "/opentelemetry.proto.common.v1.rs"
                ));
            }
        }
        pub mod resource {
            pub mod v1 {
                include!(concat!(
                    env!("OUT_DIR"),
                    "/opentelemetry.proto.resource.v1.rs"
                ));
            }
        }
        pub mod profiles {
            pub mod v1development {
                include!(concat!(
                    env!("OUT_DIR"),
                    "/opentelemetry.proto.profiles.v1development.rs"
                ));
            }
        }
    }
}

// Re-export commonly used types
pub use opentelemetry::proto::common::v1::*;
pub use opentelemetry::proto::profiles::v1development::*;
pub use opentelemetry::proto::resource::v1::*;
