[package]
name = "profiling-crashtracking-receiver"
rust-version.workspace = true
edition.workspace = true
version.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
chrono = "0.4.31"
uuid = { version = "1.4.1", features = ["v4"] }
datadog-profiling = { path = "../profiling"}
hyper = "0.14.27"
libc = "0.2.149"
nix = { version = "0.27.1", features = ["process"] }
os_info = "3.7.0"
serde_json = "1.0.107"
