# Unless explicitly stated otherwise all files in this repository are licensed under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2021-Present Datadog, Inc.

[package]
name = "datadog-library-config"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["lib"]
bench = false

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.34"
anyhow = "1.0"
known-folders = "1.2.0"

[target.'cfg(windows)'.dependencies]
winreg = "0.55"

[dev-dependencies]
tempfile = { version = "3.3" }
