[package]
name = "dd-trace-filter"
version = "0.1.0"
authors = ["Stephen Belanger <stephen.belanger@datadoghq.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib", "staticlib"]
build = "build.rs"

[features]
default = []
wasm = ["console_error_panic_hook"]
ffi = []

[build-dependencies]
libc = "0.2"
cbindgen = "0.1"

[dependencies]
rmp = "0.8.12"
rmp-serde = "1.1.2"
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen = "0.2.84"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.34"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
