# Unless explicitly stated otherwise all files in this repository are licensed under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2021-Present Datadog, Inc.

[package]
name = "datadog-sidecar-ffi"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
ddtelemetry = { path = "../ddtelemetry" }
datadog-sidecar = { path = "../sidecar" }
datadog-trace-utils = { path = "../trace-utils" }
datadog-ipc = { path = "../ipc" }
ddcommon = { path = "../ddcommon" }
ddcommon-ffi = { path = "../ddcommon-ffi" }
ddtelemetry-ffi = { path = "../ddtelemetry-ffi" }
paste = "1"
libc = "0.2"

[dev-dependencies]
hyper = { version = "0.14", default-features = false }
tempfile = {version = "3.3"}
