# Copyright 2021-Present Datadog, Inc. https://www.datadoghq.com/
# SPDX-License-Identifier: Apache-2.0

[package]
name = "datadog-sidecar-ffi"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
bench = false

[dependencies]
ddtelemetry = { path = "../ddtelemetry" }
datadog-sidecar = { path = "../sidecar" }
datadog-trace-utils = { path = "../trace-utils" }
datadog-ipc = { path = "../ipc" }
ddcommon = { path = "../ddcommon" }
ddcommon-ffi = { path = "../ddcommon-ffi", default-features = false }
ddcommon-net1 = { path = "../ddcommon-net1" }
ddtelemetry-ffi = { path = "../ddtelemetry-ffi", default-features = false }
datadog-remote-config = { path = "../remote-config" }
datadog-live-debugger = { path = "../live-debugger" }
paste = "1"
libc = "0.2"
dogstatsd-client = { path = "../dogstatsd-client" }

[dev-dependencies]
hyper = { version = "0.14", features = ["backports", "deprecated"], default-features = false }
tempfile = { version = "3.3" }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    "cfg(coverage_nightly)",
    'cfg(feature, values("prefer_dynamic"))',
] }
