// Copyright 2026-Present Datadog, Inc. https://www.datadoghq.com/
// SPDX-License-Identifier: Apache-2.0

use std::io::Result;

#[cfg(feature = "generate-protobuf")]
use {
    std::env,
    std::fs::File,
    std::io::{Read, Write},
    std::path::Path,
};

// to re-generate the protobuf structs, run:
//   cargo build -p libdd-healthplatform --features generate-protobuf
fn main() -> Result<()> {
    #[cfg(feature = "generate-protobuf")]
    {
        std::env::set_var("PROTOC", protoc_bin_vendored::protoc_bin_path().unwrap());
        generate_protobuf();
    }
    #[cfg(not(feature = "generate-protobuf"))]
    {
        println!("cargo:rerun-if-changed=build.rs");
    }

    Ok(())
}

#[cfg(feature = "generate-protobuf")]
fn generate_protobuf() {
    let cur_working_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let current_working_dir_path = Path::new(&cur_working_dir);
    let output_path = current_working_dir_path.join("src");

    let mut config = prost_build::Config::new();
    config.out_dir(output_path.clone());
    // Use BTreeMap for all map fields so the generated code stays no_std-clean.
    // (HashMap requires the std feature on prost's encoding side.)
    config.btree_map(["."]);

    // prost-build maps `.google.protobuf` types to `::prost_types` automatically; we
    // rely on prost-types' bundled descriptor for google/protobuf/struct.proto so we
    // don't have to vendor it ourselves.
    config
        .compile_protos(&["src/pb/healthplatform.proto"], &["src/pb"])
        .unwrap();

    // prost-build emits a file named after the proto package: datadog.healthplatform.rs.
    // Rename to healthplatform.rs so the include! path in lib.rs stays short.
    let generated = output_path.join("datadog.healthplatform.rs");
    let target = output_path.join("healthplatform.rs");
    std::fs::rename(&generated, &target).unwrap();

    let license = b"// Copyright 2026-Present Datadog, Inc. https://www.datadoghq.com/
// SPDX-License-Identifier: Apache-2.0
//
// @generated by prost-build from src/pb/healthplatform.proto.
// Do not edit by hand; run `cargo build -p libdd-healthplatform --features generate-protobuf`.

";
    prepend_to_file(license, &target);
}

#[cfg(feature = "generate-protobuf")]
fn prepend_to_file(data: &[u8], file_path: &Path) {
    let mut f = File::open(file_path).unwrap();
    let mut content = data.to_owned();
    f.read_to_end(&mut content).unwrap();

    let mut f = File::create(file_path).unwrap();
    f.write_all(content.as_slice()).unwrap();
}
