[package]
name = "symbolizer-ffi"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib"]

[target.'cfg(not(target_os = "windows"))'.dependencies]
blazesym-c = { git = "https://github.com/libbpf/blazesym.git", rev = "db01d98008ad09c2683490ae21eedba218f91aa2" }
