[package]
name = "symbolizer-ffi"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib"]

[target.'cfg(not(target_os = "windows"))'.dependencies]
blazesym = {version = "=0.2.0-alpha.10", features = ["apk", "demangle", "dwarf", "gsym"] }

[dev-dependencies]
env_logger = "0.10"
libc = "0.2.137"
test-log = {version = "0.2.13", default-features = false, features = ["trace"]}
tracing-subscriber = {version = "0.3", default-features = false, features = ["env-filter", "fmt"]}
