[package]
name = "symbolizer-ffi"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib"]

[dependencies]
blazesym = "0.2.0-alpha.9"
