# See https://github.com/mozilla/cbindgen/blob/master/docs.md#cbindgentoml

language = "C"
cpp_compat = true
include_guard = "__symbolizer_h_"
usize_is_size_t = true

[export]
item_types = ["globals", "enums", "structs", "unions", "typedefs", "opaque", "functions"]

[export.rename]
"Addr" = "uintptr_t"
"Symbolizer" = "struct blaze_symbolizer"

[fn]
args = "Vertical"
rename_args = "none"

[struct]
associated_constants_in_body = true
derive_eq = true
derive_ostream = true

[enum]
add_sentinel = false
derive_helper_methods = true
derive_ostream = true

[macro_expansion]
bitflags = true
