[package]
name = "datadog-ddsketch"
description = "Minimal implementation of Datadog's DDSketch"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.11.6"

[build-dependencies]
prost-build = { version = "0.11.9", optional = true  }
protoc-bin-vendored = { version = "3.0.0", optional = true }

[features]
generate-protobuf = ["dep:prost-build", "dep:protoc-bin-vendored"]
