[package]
edition = "2021"
name = "spawn_worker"
version = "0.0.1"

[lib]
bench = false

[dependencies]
anyhow = { version = "1.0" }
io-lifetimes = { version = "1.0" }

[build-dependencies]
cc_utils = {path = "../tools/cc_utils"}

[dependencies.windows]
features = [
  "Win32_Foundation",
  "Win32_Security",
  "Win32_System_Threading",
  "Win32_System_LibraryLoader",
  "Win32_System_Diagnostics_Debug",
  "Win32_System_Kernel",
]
version = "0.48"

[target.'cfg(windows)'.dependencies]
winapi = { version = "=0.2.8" }
kernel32-sys = "0.2.2"
fastrand = "2.0.1"

[target.'cfg(not(windows))'.dependencies]
memfd = { version = "0.6" }
nix = { version = "0.24" }
tempfile = { version = "3.3" }

[target.'cfg(windows)'.dev-dependencies]
tempfile = { version = "3.3" }

[target.'cfg(not(windows))'.dev-dependencies]
rlimit = {version = "0.9"}
