[package]
edition = "2021"
name = "spawn_worker"
version = "0.0.1"

[dependencies]
anyhow = { version = "1.0" }
memfd = { version = "0.6" }
nix = { version = "0.24" }
tempfile = { version = "3.3" }
io-lifetimes = { version = "1.0" }

[build-dependencies]
cc_utils = {path = "../tools/cc_utils"}

[dev-dependencies]
tempfile = {version = "3.3"}

[dependencies.windows]
features = [
  "Win32_Foundation",
  "Win32_System_Threading",
  "Win32_System_LibraryLoader",
  "Win32_System_Diagnostics_Debug",
  "Win32_System_Kernel",
]
version = "0.48"

[target.'cfg(not(windows))'.dev-dependencies]
rlimit = {version = "0.9"}
