[package]
edition = "2021"
name = "spawn_worker"
version = "0.0.1"

[dependencies]
anyhow = { version = "1.0" }
libc = { version = "0.2" }
memfd = { version = "0.6" }
nix = { version = "0.26" }
tempfile = { version = "3" }

[build-dependencies]
cc_utils = { path = "../tools/cc_utils" }

[dev-dependencies]
tempfile = { version = "3.3" }
