[package]
edition = "2021"
name = "spawn_worker"
version = "0.0.1"

[lib]
bench = false

[dependencies]
anyhow = { version = "1.0" }
io-lifetimes = { version = "1.0" }
fastrand = "2.0.1"
libc = "0.2"

[build-dependencies]
cc = "1.0"
ddcommon = { path = "../ddcommon" }

[dependencies.windows]
features = [
  "Win32_Foundation",
  "Win32_Security",
  "Win32_System_Threading",
  "Win32_System_LibraryLoader",
  "Win32_System_Diagnostics_Debug",
  "Win32_System_Kernel",
]
version = "0.51.1"

[target.'cfg(windows)'.dependencies]
winapi = { version = "=0.2.8" }
kernel32-sys = "0.2.2"

[target.'cfg(not(windows))'.dependencies]
memfd = { version = "0.6" }
nix = { version = "0.29", features = ["dir", "process"] }
tempfile = { version = "3.3" }

[target.'cfg(windows)'.dev-dependencies]
tempfile = { version = "3.3" }

[target.'cfg(not(windows))'.dev-dependencies]
rlimit = {version = "0.9"}

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage,coverage_nightly)'] }

