issuer: https://gitlab.ddbuild.io

subject_pattern: "project_path:DataDog/.*"

claim_pattern:
  project_id: "2260"
  ref: "(main|release|igor/versioning/.*)" # TODO: remove testing branch and uncomment ref_protected
  # ref_protected: "true"

permissions:
  contents: write
  pull_requests: write
