issuer: https://gitlab.ddbuild.io

subject_pattern: "project_path:DataDog/.*"

claim_pattern:
  project_id: "2260"
  ref: "refs/heads/(main|release)"
  # ref_protected: "true"
  pipeline_source: "push"

permissions:
  contents: write
