issuer: https://token.actions.githubusercontent.com

subject_pattern: "repo:DataDog/libdatadog.*"

claim_pattern:
  ref: "(main|release|julio/.*)" # TODO: remove testing branch and uncomment ref_protected
  # ref_protected: "true"

permissions:
  members: read
  metadata: read
