issuer: https://token.actions.githubusercontent.com

subject_pattern: "repo:DataDog/libdatadog.*"

claim_pattern:
  ref: "refs/heads/(main|release)"
  ref_protected: "true"

permissions:
  members: read
  metadata: read
