issuer: https://token.actions.githubusercontent.com

subject_pattern: "repo:DataDog/libdatadog.*"

claim_pattern:
  ref: "refs/heads/(main|release|igor/.*|julio/.*)"
  ref_protected: "true"
  email: ".*@datadoghq.com"
  # job_workflow_ref: DataDog/libdatadog/\.github/workflows/release-proposal-dispatch\.yml@.+

permissions:
  contents: write
  pull_requests: write
