[package]
name = "tinybytes"
description = "Tiny implementation of a bytes::Bytes like type that supports AsRef<[u8]>"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
crate-type = ["lib"]
bench = false

[dev-dependencies]
monkey_test = "0.7.3"
once_cell = "1.8"
pretty_assertions = "1.3"
#proptest = {version = "1.5", features = ["std"], no-default-features = true}
test-case = "2.2"
