[package]
name = "tinybytes"
description = "Tiny implementation of a bytes::Bytes like type that supports AsRef<[u8]>"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
crate-type = ["lib"]
bench = false

[dev-dependencies]
#monkey_test = "0.7.3"
once_cell = "1.8"
pretty_assertions = "1.3"
proptest = {version = "1.5", features = ["std"], default-features = false}
test-case = "2.2"
# panic-message = "0.3"
# num-traits = "0.2.18"
# rand = {version = "0.8", features = ["alloc", "std"], default-features = false}
# rand_chacha = {version = "0.3", default-features = false}
# rand_xorshift = {version = "0.3"}
