// Copyright 2026-Present Datadog, Inc. https://www.datadoghq.com/
// SPDX-License-Identifier: Apache-2.0
//
// @generated by prost-build from src/pb/healthplatform.proto.
// Do not edit by hand; run `cargo build -p libdd-healthplatform --features generate-protobuf`.

// This file is @generated by prost-build.
/// Issue represents an individual issue to be reported
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Issue {
    /// ID is the unique identifier for the issue
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// IssueName is the human-readable name for the issue
    #[prost(string, tag = "2")]
    pub issue_name: ::prost::alloc::string::String,
    /// Title is the short title/headline of the issue
    #[prost(string, tag = "3")]
    pub title: ::prost::alloc::string::String,
    /// Description is the detailed description of the issue
    #[prost(string, tag = "4")]
    pub description: ::prost::alloc::string::String,
    /// Category indicates the type/category of the issue (e.g., permissions, connectivity, etc.)
    #[prost(string, tag = "5")]
    pub category: ::prost::alloc::string::String,
    /// Location indicates where the issue occurred (e.g., core agent, log agent, etc.)
    #[prost(string, tag = "6")]
    pub location: ::prost::alloc::string::String,
    /// Severity indicates the impact level of the issue
    #[prost(string, tag = "7")]
    pub severity: ::prost::alloc::string::String,
    /// DetectedAt is the timestamp when the issue was detected
    #[prost(string, tag = "8")]
    pub detected_at: ::prost::alloc::string::String,
    /// Source is the sub-agent or product that reported the issue
    /// (e.g., "logs", "apm", "error-tracking", "network-monitoring")
    #[prost(string, tag = "9")]
    pub source: ::prost::alloc::string::String,
    /// Extra is optional complementary structured information
    #[prost(message, optional, tag = "10")]
    pub extra: ::core::option::Option<::prost_types::Struct>,
    /// Remediation provides steps to fix the issue
    #[prost(message, optional, tag = "11")]
    pub remediation: ::core::option::Option<Remediation>,
    /// Tags are additional labels for the issue
    #[prost(string, repeated, tag = "12")]
    pub tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// PersistedIssue tracks the lifecycle state of the issue
    #[prost(message, optional, tag = "13")]
    pub persisted_issue: ::core::option::Option<PersistedIssue>,
}
/// Remediation represents remediation steps for an issue
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Remediation {
    /// Summary is a brief description of the remediation
    #[prost(string, tag = "1")]
    pub summary: ::prost::alloc::string::String,
    /// Steps are the ordered steps to fix the issue
    #[prost(message, repeated, tag = "2")]
    pub steps: ::prost::alloc::vec::Vec<RemediationStep>,
    /// Script is an automated script to fix the issue
    #[prost(message, optional, tag = "3")]
    pub script: ::core::option::Option<Script>,
}
/// RemediationStep represents a single remediation step
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RemediationStep {
    /// Order is the sequence number of the step
    #[prost(int32, tag = "1")]
    pub order: i32,
    /// Text is the description of what to do
    #[prost(string, tag = "2")]
    pub text: ::prost::alloc::string::String,
}
/// Script represents a remediation script
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Script {
    /// Language is the scripting language (e.g., bash, powershell, python, javascript)
    #[prost(string, tag = "1")]
    pub language: ::prost::alloc::string::String,
    /// LanguageVersion is the required interpreter version (e.g., "3.8+" for Python, ">=14" for Node.js)
    #[prost(string, tag = "2")]
    pub language_version: ::prost::alloc::string::String,
    /// Filename is the suggested filename for the script
    #[prost(string, tag = "3")]
    pub filename: ::prost::alloc::string::String,
    /// RequiresRoot indicates if the script needs root privileges
    #[prost(bool, tag = "4")]
    pub requires_root: bool,
    /// Content is the actual script content
    #[prost(string, tag = "5")]
    pub content: ::prost::alloc::string::String,
}
/// HostInfo represents the host information in the health report
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostInfo {
    /// Hostname is the hostname of the reporting host
    #[prost(string, tag = "1")]
    pub hostname: ::prost::alloc::string::String,
    /// AgentVersion is the version of the agent
    #[prost(string, optional, tag = "2")]
    pub agent_version: ::core::option::Option<::prost::alloc::string::String>,
    /// ParIDs are the partition/organization IDs
    #[prost(string, repeated, tag = "3")]
    pub par_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// HealthReport represents the formatted health report structure sent to Datadog intake
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HealthReport {
    /// SchemaVersion is the version of the schema
    #[prost(string, tag = "1")]
    pub schema_version: ::prost::alloc::string::String,
    /// EventType is the type of event
    #[prost(string, tag = "2")]
    pub event_type: ::prost::alloc::string::String,
    /// EmittedAt is the timestamp when the report was emitted
    #[prost(string, tag = "3")]
    pub emitted_at: ::prost::alloc::string::String,
    /// Host contains host information
    #[prost(message, optional, tag = "4")]
    pub host: ::core::option::Option<HostInfo>,
    /// Issues is a map of check IDs to their issues
    #[prost(btree_map = "string, message", tag = "5")]
    pub issues: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        Issue,
    >,
    /// Service is the service that detected the issue (datadog-agent, cluster-agent, backend service)
    #[prost(string, tag = "6")]
    pub service: ::prost::alloc::string::String,
}
/// JSONAPIMeta represents metadata in JSON:API format
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct JsonapiMeta {
    /// SchemaVersion is the version of the schema
    #[prost(string, tag = "1")]
    pub schema_version: ::prost::alloc::string::String,
    /// EventType is the type of event
    #[prost(string, tag = "2")]
    pub event_type: ::prost::alloc::string::String,
    /// EmittedAt is the timestamp when the report was emitted
    #[prost(string, tag = "3")]
    pub emitted_at: ::prost::alloc::string::String,
}
/// JSONAPIResponse represents the JSON:API wrapper for health reports
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JsonapiResponse {
    /// Data contains the health report
    #[prost(message, optional, tag = "1")]
    pub data: ::core::option::Option<HealthReport>,
    /// Meta contains optional metadata
    #[prost(message, optional, tag = "2")]
    pub meta: ::core::option::Option<JsonapiMeta>,
}
/// IssueReport represents a lightweight issue report from an integration
/// The health platform fills in all metadata and remediation based on the issue ID
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IssueReport {
    /// IssueID is the unique identifier for the type of issue
    /// The health platform registry uses this to look up all issue details
    #[prost(string, tag = "1")]
    pub issue_id: ::prost::alloc::string::String,
    /// Context provides variables for filling in templates
    /// (e.g., {"dockerDir": "/var/lib/docker", "os": "linux"})
    #[prost(btree_map = "string, string", tag = "2")]
    pub context: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// Tags are optional additional labels for filtering and categorization
    /// These are appended to the default tags from the registry
    #[prost(string, repeated, tag = "3")]
    pub tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// PersistedIssue tracks the lifecycle state of a single issue
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PersistedIssue {
    /// State is the current lifecycle state
    #[prost(enumeration = "IssueState", tag = "1")]
    pub state: i32,
    /// FirstSeen is the timestamp when the issue was first detected
    #[prost(string, tag = "2")]
    pub first_seen: ::prost::alloc::string::String,
    /// LastSeen is the timestamp when the issue was last observed
    #[prost(string, tag = "3")]
    pub last_seen: ::prost::alloc::string::String,
    /// ResolvedAt is the timestamp when the issue was resolved
    #[prost(string, optional, tag = "4")]
    pub resolved_at: ::core::option::Option<::prost::alloc::string::String>,
}
/// IssueState represents the lifecycle state of an issue
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum IssueState {
    Unspecified = 0,
    New = 1,
    Ongoing = 2,
    Resolved = 3,
}
impl IssueState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ISSUE_STATE_UNSPECIFIED",
            Self::New => "ISSUE_STATE_NEW",
            Self::Ongoing => "ISSUE_STATE_ONGOING",
            Self::Resolved => "ISSUE_STATE_RESOLVED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ISSUE_STATE_UNSPECIFIED" => Some(Self::Unspecified),
            "ISSUE_STATE_NEW" => Some(Self::New),
            "ISSUE_STATE_ONGOING" => Some(Self::Ongoing),
            "ISSUE_STATE_RESOLVED" => Some(Self::Resolved),
            _ => None,
        }
    }
}
