// Copyright 2026-Present Datadog, Inc. https://www.datadoghq.com/
// SPDX-License-Identifier: Apache-2.0

//! Rust types for Datadog's `agent-payload` healthplatform protobuf schema.
//!
//! The crate is `no_std + alloc`. Encoding is always available; the public
//! `decode` module is gated behind the `decode` cargo feature.
//!
//! Note: prost emits both encode and decode implementations on every generated
//! message, so the `decode` feature gates the *public helper surface* only, not
//! the code-size cost of the decoders themselves.

#![cfg_attr(not(test), no_std)]
#![cfg_attr(not(test), deny(clippy::panic))]
#![cfg_attr(not(test), deny(clippy::unwrap_used))]
#![cfg_attr(not(test), deny(clippy::expect_used))]
#![cfg_attr(not(test), deny(clippy::todo))]
#![cfg_attr(not(test), deny(clippy::unimplemented))]

extern crate alloc;

pub use prost;
pub use prost_types;

mod healthplatform {
    // Generated by prost-build; checked in. Regenerate with the `generate-protobuf` feature.
    include!("healthplatform.rs");
}

pub use healthplatform::*;

/// Encoding helpers; always available.
pub mod encode {
    use crate::HealthReport;
    use alloc::vec::Vec;
    use prost::Message;

    /// Encode a `HealthReport` to a freshly allocated protobuf byte vector.
    pub fn encode_health_report(report: &HealthReport) -> Vec<u8> {
        report.encode_to_vec()
    }
}

/// Decoding helpers; gated behind the `decode` cargo feature.
#[cfg(feature = "decode")]
pub mod decode {
    use crate::HealthReport;
    use prost::{DecodeError, Message};

    /// Decode a `HealthReport` from a protobuf byte slice.
    pub fn decode_health_report(bytes: &[u8]) -> Result<HealthReport, DecodeError> {
        HealthReport::decode(bytes)
    }
}
