[package]
name = "datadog-trace-protobuf"
authors = ["David Lee <david.lee@datadoghq.com>"]
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
prost = "0.11.6"
serde = { version = "1.0.145", features = ["derive"] }
serde_bytes = "0.11.9"

[build-dependencies]
prost-build = { version = "0.11.9", optional = true  }
protoc-bin-vendored = { version = "3.0.0", optional = true }

[features]
generate-protobuf = ["dep:prost-build", "dep:protoc-bin-vendored"]

[dev-dependencies]
serde_json = "1.0.117"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
