# Copyright 2021-Present Datadog, Inc. https://www.datadoghq.com/
# SPDX-License-Identifier: Apache-2.0

[package]
name = "ddtelemetry-ffi"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
bench = false

[features]
default = ["cbindgen", "expanded_builder_macros"]
cbindgen = ["build_common/cbindgen", "ddcommon-ffi/cbindgen", "expanded_builder_macros"]
expanded_builder_macros = []

[build-dependencies]
build_common = { path = "../build-common" }

[dependencies]
ddtelemetry = { version = "1.0.0", path = "../libdd-telemetry", package = "libdd-telemetry" }
ddcommon = { version = "1.0.0", path = "../libdd-common", package = "libdd-common" }
ddcommon-ffi = { path = "../libdd-common-ffi", package = "libdd-common-ffi", default-features = false }
function_name = "0.3"
libc = "0.2"
paste = "1"

[dev-dependencies]
tempfile = {version = "3.3"}
