# Copyright 2021-Present Datadog, Inc. https://www.datadoghq.com/
# SPDX-License-Identifier: Apache-2.0

[package]
name = "ddtelemetry-ffi"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
bench = false

[features]
default = ["cbindgen", "expanded_builder_macros"]
cbindgen = ["build_common/cbindgen", "ddcommon-ffi/cbindgen", "expanded_builder_macros"]
expanded_builder_macros = []

[build-dependencies]
build_common = { path = "../build-common" }

[dependencies]
ddtelemetry = { path = "../ddtelemetry" }
ddcommon = { path = "../ddcommon" }
ddcommon-ffi = { path = "../ddcommon-ffi", default-features = false }
ddcommon-net1 = { path = "../ddcommon-net1" }
paste = "1"
libc = "0.2"

[dev-dependencies]
tempfile = {version = "3.3"}
