# Unless explicitly stated otherwise all files in this repository are licensed under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2021-Present Datadog, Inc.

[package]
name = "ddtelemetry-ffi"
version = "2.2.0"
edition = "2021"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
ddtelemetry = { path = "../ddtelemetry" }
datadog-ipc = { path = "../ipc" }
ddcommon-ffi = { path = "../ddcommon-ffi" }
paste = "1"
libc = "0.2"

[dev-dependencies]
tempfile = {version = "3.3"}
