FROM ghcr.io/cross-rs/x86_64-unknown-linux-gnu:main-centos@sha256:92e34415f6c4d771ab5797ce62cb658a2134737a02b609238697f7fc6279770e

RUN sed -i s/mirror.centos.org/vault.centos.org/g /etc/yum.repos.d/*.repo \
    && sed -i s/^#.*baseurl=http/baseurl=http/g /etc/yum.repos.d/*.repo \
    && sed -i s/^mirrorlist=http/#mirrorlist=http/g /etc/yum.repos.d/*.repo \
    && yum update -y \
    && yum install -y centos-release-scl

# Find and replace mirror.centos.org with vault.centos.org a second time
# installing centos-release-scl may have added new repos that need to be updated
RUN sed -i s/mirror.centos.org/vault.centos.org/g /etc/yum.repos.d/*.repo \
    && sed -i s/^#.*baseurl=http/baseurl=http/g /etc/yum.repos.d/*.repo \
    && sed -i s/^mirrorlist=http/#mirrorlist=http/g /etc/yum.repos.d/*.repo \
    && yum update -y \
    && yum install -y devtoolset-11 autoconf automake libtool \
    && yum clean all

ENV PATH="/opt/rh/devtoolset-11/root/usr/bin:$PATH"

ARG NEXTEST_VERSION=0.9.96
ARG NEXTEST_SHA256=34589b4debb468d84f6ab81652b7bc42ac672162a3dfc8063abe6fd850898150
RUN curl -fsSL --retry 3 -o /tmp/nextest.tar.gz \
      "https://github.com/nextest-rs/nextest/releases/download/cargo-nextest-${NEXTEST_VERSION}/cargo-nextest-${NEXTEST_VERSION}-x86_64-unknown-linux-musl.tar.gz" \
    && echo "${NEXTEST_SHA256}  /tmp/nextest.tar.gz" | sha256sum -c - \
    && tar zxf /tmp/nextest.tar.gz -C /usr/local/bin \
    && rm /tmp/nextest.tar.gz
