// Copyright 2023-Present Datadog, Inc. https://www.datadoghq.com/
// SPDX-License-Identifier: Apache-2.0

// This file is @generated by prost-build.
pub mod pb {
    include!("pb.rs");
    pub mod idx {
        include!("pb.idx.rs");
    }
}
pub mod remoteconfig {
    include!("remoteconfig.rs");
}
