name: All checks pass
on:
    pull_request:
    push:
      branches:
        - main
jobs:
    allchecks:
        runs-on: ubuntu-latest
        permissions:
            checks: read
            contents: read
        steps:
            - uses: wechuli/allcheckspassed@v1
            with:
                delay: '3'
                retries: '20'
                polling_interval: '1'
