on:
  push:
    branches:
      - $default-branch
      - pawel/automatically_updated_license-3rd-party.yaml
jobs:
  execute:
    name: Create PR if Lincense-3rdparty needs to be updated
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: stat LICENSE-3rdparty.yml
      - run: cargo install cargo-bundle-licenses
      - name: "Generate new LICENSE-3rdparty.yml and check against the previous" 
        env: 
          CARGO_HOME: "/tmp/dd-cargo"
        run: > 
          cargo bundle-licenses \
            --format yaml \
            --output LICENSE-3rdparty.yml 
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "[auto] update LICENSE-3rdparty file"
          title: "[auto] update LICENSE-3rdparty file"
          body: "automated License file update"
          branch: "auto-bot-ci/update-license-3rdparty"
          delete-branch: true
          base: "${{ github.event.repository.default_branch }}"
