name: Build the Serverless Agent
on: push

jobs:
  build-linux-musl:
    name: Build Linux Musl
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            ref: david.lee/mini-agent-azure-tags
      - name: Install musl dependencies
        run: rustup target add x86_64-unknown-linux-musl && sudo apt-get install musl-tools
      - name: Build project
        run: cargo build --release -p datadog-serverless-trace-mini-agent --target x86_64-unknown-linux-musl
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: datadog-serverless-agent-linux-amd64
          path: target/x86_64-unknown-linux-musl/release/datadog-serverless-trace-mini-agent
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            ref: david.lee/mini-agent-azure-tags
      - name: Build project
        run: cargo build --release -p datadog-serverless-trace-mini-agent
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: datadog-serverless-agent-windows-amd64
          path: target/release/datadog-serverless-trace-mini-agent.exe

