name: Lint experiments
on:
  push:
    paths:
      - 'experimental/**' # Only run action when experiments have changed

env: 
  CARGO_TERM_COLOR: always
    
jobs:
  rustfmt:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./experimental
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Cache
        uses: ./.github/actions/cache
      - name: Install latest nightly toolchain and rustfmt
        run: rustup update nightly && rustup default nightly && rustup component add rustfmt
  clippy:
    name: "clippy #${{ matrix.rust_version }}"
    strategy:
      fail-fast: false
      matrix:
        rust_version: ["stable"]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./experimental
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Cache
        uses: ./.github/actions/cache
        with:
          rust_version: ${{ matrix.rust_version }}
      - name: Install ${{ matrix.rust_version }} toolchain and clippy
        run: rustup install ${{ matrix.rust_version }} && rustup default ${{ matrix.rust_version }} && rustup component add clippy
      - run: cargo clippy --all-targets --all-features -- -D warnings