name: Test experiments
on:
  push:
    paths:
      - 'experimental/**' # Only run action when experiments have changed

defaults:
  run:
    working-directory: ./experimental

env: 
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: "cargo test --workspace #${{ matrix.platform }} ${{ matrix.rust_version }}"
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [windows-latest, ubuntu-latest, macos-12]
        rust_version: [""]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Cache
        uses: ./.github/actions/cache
        with:
          rust_version: ${{ matrix.rust_version }}
      - name: Install Rust ${{ matrix.rust_version }}
        if: ${{ matrix.rust_version != '' }}
        run: rustup install ${{ matrix.rust_version }} && rustup default ${{ matrix.rust_version }}
      - id: rust-version
        run: echo "version=$(rustc --version)" >> $GITHUB_OUTPUT
      - name: "[${{ steps.rust-version.outputs.version}}] cargo build --workspace --verbose"
        run: cargo build --workspace --verbose
      - name: "[${{ steps.rust-version.outputs.version}}] cargo test --workspace --verbose"
        run: cargo test --workspace --verbose
        env:
          RUST_BACKTRACE: 1


  