name: Fuzz test
on:
  push:

jobs:
  run-fuzz:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      run: |
        set -e
        rustup set profile minimal
        rustup toolchain install nightly
        rustup default nightly
    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-bolero
    - uses: sergeysova/jq-action@v2
    - run: |
        set -e
        DIRS="alloc profiling"
        for dir in $DIRS;
        do
          cd $dir && cargo bolero list | \
          jq -r '[.package, .test] | @tsv' | \
          while read -r package test;
          do
            cargo bolero test -T 1min --package $package $test
          done
        done
