name: Fuzz test
on:
  push:

jobs:
  run-fuzz:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [alloc, profiling, ddcommon-ffi, trace-utils]
    env:
      CARGO_TERM_COLOR: always
    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      run: |
        set -e
        rustup set profile minimal
        rustup toolchain install nightly-2024-10-21
        rustup default nightly-2024-10-21
    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-bolero
    - run: |
        set -e
        # cargo bolero list outputs {"package":"package-name","test":"test-name"}
        pushd ${{ matrix.directory }}
        cargo bolero list | \
        # And the following command will parse package-name's and test-name's one in each line
        grep -oP '"(package|test)"\s*:\s*"\K[^"]+' | \
        # awk will stitch package and test names back separated by a tab
        awk 'NR%2{printf "%s\t", $0; next}1' | \
        while read -r package test;
        do
          echo "****** Starting bolero test for $package $test ******" 1>&2
          cargo bolero test -T 30s --package $package $test
        done
        popd
