name: Lint
on:
  push:
env:
  CARGO_TERM_COLOR: always

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
        with:
          submodules: recursive
      - name: Run actionlint
        uses: devops-actions/actionlint@c6744a34774e4e1c1df0ff66bdb07ec7ee480ca0 # 0.1.9
        with:
          shellcheck_opts: '-e SC2086'
  rustfmt:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
      CARGO_INCREMENTAL: 0
    steps:
      - name: Checkout sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
        with:
          submodules: recursive
      - name: Install nightly-2026-02-08 toolchain and rustfmt
        run: rustup set profile minimal && rustup install nightly-2026-02-08 && rustup default nightly-2026-02-08 && rustup component add rustfmt
      - name: Cache [rust]
        uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # 2.8.1
        with:
          cache-targets: true # cache build artifacts
          cache-bin: true # cache the ~/.cargo/bin directory
      - run: cargo fmt --all -- --check
  clippy:
    name: "clippy #${{ matrix.platform }} ${{ matrix.rust_version }}"
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        rust_version: ["1.84.1", "stable", "nightly-2026-02-08"]
        platform: [windows-latest, ubuntu-latest]
    steps:
      - name: Checkout sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
        with:
          submodules: recursive
      - name: Install ${{ matrix.rust_version }} toolchain and clippy
        run: rustup set profile minimal && rustup install ${{ matrix.rust_version }} && rustup default ${{ matrix.rust_version }} && rustup component add clippy
      - name: Cache [rust]
        uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # 2.8.1
        with:
          cache-targets: true # cache build artifacts
          cache-bin: true # cache the ~/.cargo/bin directory
      - name: Run clippy on ${{ matrix.platform }} ${{ matrix.rust_version }}
        shell: bash
        run: |
          if [[ "${{ matrix.platform }}" == "windows-latest" ]]; then
            export AWS_LC_FIPS_SYS_NO_ASM=1
          fi
          # shellcheck disable=SC2046
          cargo clippy --workspace --all-targets --all-features -- -D warnings $([ ${{ matrix.rust_version }} = 1.84.1 ] || echo -Aclippy::manual_is_multiple_of)

  licensecheck:
    runs-on: ubuntu-latest
    name: "Presence of licence headers"
    steps:
      - name: Checkout sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - name: Install licensecheck
        run: sudo apt-get install -y licensecheck
      - name: Check licenses
        # Exclude symbolizer-ffi from the checks (mostly imported code)
        run: '! find . \( -name "*.rs" -o -name "*.c" -o -name "*.sh" \)  -not -path "./symbolizer-ffi/*" -not -path "./datadog-ipc/plugins/*" -not -path "./datadog-ipc/tarpc/*" -print0 | xargs -0 licensecheck -c ".*" | grep -v "Apache License 2.0"'

  license-3rdparty:
    runs-on: ubuntu-latest
    name: "Valid LICENSE-3rdparty.csv"
    steps:
      - name: Checkout sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      # Keep version in sync with: scripts/update_license_3rdparty.sh (TOOL_VERSION) and scripts/Dockerfile.license (ARG TOOL_VERSION)
      - name: Cache dd-rust-license-tool
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # 4.2.2
        with:
          path: |
            ~/.cargo/registry/
            ~/.cargo/git/db/
            ~/.cargo/bin/dd-rust-license-tool
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
          key: dd-rust-license-tool-1.0.6-v2
      - run: cargo install --list | grep -qF "dd-rust-license-tool v1.0.6" || cargo install dd-rust-license-tool --version "1.0.6" --locked
      - name: Generate new LICENSE-3rdparty.csv and check against the previous
        run: |
          if ! dd-rust-license-tool dump > /tmp/CI.csv 2> /tmp/CI.error; then
            echo "ERROR: dd-rust-license-tool dump failed! See error output below:"
            cat /tmp/CI.error
            exit 1
          fi
          if ! diff /tmp/CI.csv LICENSE-3rdparty.csv; then
            echo "Differences detected in LICENSE-3rdparty.csv."
            echo "Please run './scripts/update_license_3rdparty.sh' to update the file and commit the changes."
            exit 1
          fi
          echo "No differences found."
      - name: Export generated license file on failure
        if: failure()
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: LICENSE-3rdparty.csv
          path: /tmp/CI.csv
          overwrite: true

  codeowners-validator:
    runs-on: ubuntu-latest
    name: "Validate CODEOWNERS"
    steps:
      - name: Checkout sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - name: GitHub CODEOWNERS Validator
        uses: mszostok/codeowners-validator@7f3f5e28c6d7b8dfae5731e54ce2272ca384592f #v0.7.4
        # input parameters
        with:
          github_app_id: ${{ secrets.CODEOWNERS_VALIDATOR_APP_ID }}
          github_app_installation_id: ${{ secrets.CODEOWNERS_VALIDATOR_APP_INSTALLATION_ID }}
          github_app_private_key: ${{ secrets.CODEOWNERS_VALIDATOR_APP_PRIVATE_KEY }}

          # "The list of checks that will be executed. By default, all checks are executed. Possible values: files,owners,duppatterns,syntax"
          checks: "files,duppatterns,syntax"
          # "The comma-separated list of experimental checks that should be executed. By default, all experimental checks are turned off. Possible values: notowned."
          experimental_checks: "notowned"
          # The repository path in which CODEOWNERS file should be validated."
          repository_path: "."
