name: Miri test
on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-miri:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        run: |
          set -e
          rustup set profile minimal
          rustup toolchain install nightly-2024-12-16 --component miri
          rustup default nightly-2024-12-16
      - name: Install Protoc Binary
        shell: bash
        run: chmod +x ./scripts/install-protoc.sh && ./scripts/install-protoc.sh $HOME
      - uses: taiki-e/install-action@v2
        with:
          tool: nextest@0.9.92
      - run: cargo nextest archive --archive-file nextest-archive.tar.zst
      - name: Upload archive to workflow
        uses: actions/upload-artifact@v4
        with:
          name: nextest-archive
          path: nextest-archive.tar.zst

  run-miri:
    runs-on: ubuntu-latest
    needs: build-miri
    strategy:
      matrix:
        partition: [1, 2, 3, 4, 5]
    env:
      PROPTEST_CASES: 1
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        run: |
          set -e
          rustup set profile minimal
          rustup toolchain install nightly-2024-12-16 --component miri
          rustup default nightly-2024-12-16
      - uses: taiki-e/install-action@v2
        with:
          tool: nextest@0.9.92
      - run: |
          MIRIFLAGS="-Zmiri-disable-isolation" cargo miri nextest run \
            --archive-file nextest-archive.tar.zst \
            --partition count:${{ matrix.partition }}/5
      # We need to disable isolation because
      # "unsupported operation: `clock_gettime` with `REALTIME` clocks not available when isolation is enabled"
