name: Miri test
on:
  push:

jobs:
  run-miri:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
        components: miri
    - uses: taiki-e/install-action@v2
      with: 
        tool: nextest@0.9.68
    - run: MIRIFLAGS="-Zmiri-disable-isolation" cargo miri nextest run
    # We need to disable isolation because 
    # "unsupported operation: `clock_gettime` with `REALTIME` clocks not available when isolation is enabled" 
