name: Miri test
on:
  push:

jobs:
  run-miri:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        partition: [1, 2, 3, 4, 5]
    env:
      CARGO_TERM_COLOR: always
      PROPTEST_CASES: 1
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - name: Set up Rust
        run: |
          set -e
          rustup set profile minimal
          rustup toolchain install nightly-2024-12-16 --component miri
          rustup default nightly-2024-12-16
      - uses: taiki-e/install-action@2c41309d51ede152b6f2ee6bf3b71e6dc9a8b7df # 2.49.27
        with:
          tool: nextest@0.9.96
      - run: MIRIFLAGS="-Zmiri-disable-isolation" cargo miri nextest run --partition count:${{ matrix.partition }}/5
      # We need to disable isolation because
      # "unsupported operation: `clock_gettime` with `REALTIME` clocks not available when isolation is enabled"
