name: Miri test
on:
  push:
    paths:
      - 'profiling/**' # Only run action when profile related things are touched
                       # If we add other miri tests, add them here

jobs:
  profiler-observation-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
        components: miri
    - uses: actions-rs/cargo@v1
      with:
        command: miri
        args: test profile::internal::observation
