name: Miri test
on:
  push:

jobs:
  run-miri:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      run: |
        set -e
        rustup set profile minimal
        rustup toolchain install nightly --component miri 
        rustup default nightly
    - uses: taiki-e/install-action@v2
      with: 
        tool: nextest@0.9.68
    - run: MIRIFLAGS="-Zmiri-disable-isolation" cargo miri nextest run
    # We need to disable isolation because 
    # "unsupported operation: `clock_gettime` with `REALTIME` clocks not available when isolation is enabled" 
