name: Miri test
on:
  push:
    # paths:
    #   - 'profiling/**' # Only run action when profile related things are touched
    #   - 'profiling-ffi/**' # Only run action when profile related things are touched

jobs:
  profiler-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
        components: miri
    - run: cd profiling && MIRIFLAGS="-Zmiri-disable-isolation" cargo miri test
#    - run: cd ../profiling-ffi && MIRIFLAGS="-Zmiri-disable-isolation" cargo miri test
    # We need to disable isolation because 
    # "unsupported operation: `clock_gettime` with `REALTIME` clocks not available when isolation is enabled" 
