name: Publish Ruby gem
on: workflow_dispatch

concurrency: "publish-ruby" # Only one publish job at a time

jobs:
  publish-ruby:
    name: Build and push gem to RubyGems.org
    runs-on: ubuntu-24.04
    environment: "publish-ruby" # see: https://github.com/datadog/libdatadog/settings/environments
    permissions:
      id-token: write # Required for trusted publishing, see https://github.com/rubygems/release-gem
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Ruby
        uses: ruby/setup-ruby@e34163cd15f4bb403dcd72d98e295997e6a55798 # v1.238.0
        with:
          ruby-version: 'ruby'
      - name: Install dependencies
        working-directory: ruby
        run: bundle install
      - uses: rubygems/release-gem@a25424ba2ba8b387abc8ef40807c2c85b96cbe32 # v1.1.1
