name: Publish Serverless Mini Agent Binaries to NPM & PyPi
on:
  push: 
    branches:
      - david.lee/mini-agent-releasing-test
# on:
#   push:
#     tags:
#       - 'serverless-**'

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: datadog-serverless-trace-mini-agent-linux-amd64
          - os: windows-latest
            asset_name: datadog-serverless-trace-mini-agent-windows-amd64
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build project
        run: cargo build --release
      - name: Upload artifacts for release step
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.asset_name }}
          path: target/release/datadog-serverless-trace-mini-agent
  release:
    name: Zip and Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download artifacts from build step
        uses: actions/download-artifact@v3
        with:
          path: target/release/datadog-serverless-trace-mini-agent-binaries
      - name: Zip up artifacts
        run: zip -r target/release/datadog-serverless-trace-mini-agent-binaries.zip target/release/datadog-serverless-trace-mini-agent-binaries
      - name: List release directory
        run: ls ./target/release
      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     draft: true
      #     generate_release_notes: true
      #     files: |
      #       target/release/datadog-serverless-trace-mini-agent-binaries.zip
