[package]
name = "metrics"
version = "0.0.1"
edition = "2021"

[dependencies]
ddcommon = { path = "../ddcommon" }
futures = "0.3.28"
hyper = "0.14.25"
hyper-tls = "0.5.0"
serde = "1.0.159"
serde_json = "1.0.95"
tokio = { version = "1.27.0", features = ["net", "rt", "rt-multi-thread", "macros"] }
