# Copyright 2025-Present Datadog, Inc. https://www.datadoghq.com/
# SPDX-License-Identifier: Apache-2.0

max_width = 80
doc_comment_code_block_width = 80
comment_width = 80
use_small_heuristics = "Max"
imports_granularity = "Module"